; Generated by Hylian compiler (IR backend)
; Source: __tuple_test.hy
bits 64
default rel

; Target: linux
; Assemble: nasm -f elf64 <file>.asm -o <file>.o
;          # prefer pre-built: runtime/std/io.o
;          # fallback:         gcc -O2 -c runtime/std/io.c -o io.o
; Link:     gcc <file>.o io.o -o <program> -no-pie

extern malloc
extern realloc
extern strlen
extern arena_init
extern arena_alloc
extern arena_free
extern hylian_print
extern hylian_println
extern hylian_int_to_str
extern hylian_float_to_str

section .data
    _str0: db 0x5c,"n", 0
    _str0_len: equ 2
    _SYS_READ: dq 0
    _SYS_WRITE: dq 1
    _SYS_OPEN: dq 2
    _SYS_CLOSE: dq 3
    _SYS_FSTAT: dq 5
    _SYS_MMAP: dq 9
    _SYS_MUNMAP: dq 11
    _SYS_GETCWD: dq 79
    _SYS_MKDIR: dq 83
    _SYS_PREAD: dq 17
    _SYS_PWRITE: dq 18
    _SYS_EXIT: dq 60
    _SYS_FORK: dq 57
    _SYS_EXECVE: dq 59
    _SYS_WAIT4: dq 61
    _SYS_PIPE2: dq 293
    _SYS_DUP2: dq 33
    _MAP_FLAGS: dq 34

section .text
    global main

divmod:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    lea rax, [rbp - 24]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rax, [rbp - 16]
    mov [rbp - 56], rax
    mov rax, [rbp - 48]
    push rax
    mov rax, [rbp - 56]
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov [rbp - 64], rax
    mov rax, [rbp - 8]
    mov [rbp - 72], rax
    mov rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 80]
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov rax, rdx
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 24]
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 104], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

main:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov qword [rbp - 8], 0
    lea rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 32], rax
    mov qword [rbp - 16], 0
    mov rax, 17
    mov [rbp - 48], rax
    mov rax, 5
    mov [rbp - 56], rax
    mov rax, 17
    push rax
    mov rax, 5
    push rax
    pop rsi
    pop rdi
    call divmod
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 16], rax
    ; LOAD_VAR 'quotient' not found
    xor rax, rax
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    ; LOAD_VAR 'remainder' not found
    xor rax, rax
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    xor rax, rax
    mov [rbp - 96], rax
    mov rax, 0
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 8]
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 112], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

_hy_strlen:
    push rbp
    mov rbp, rsp
    sub rsp, 240
    mov [rbp - 8], rdi
    mov qword [rbp - 16], 0
    lea rax, [rbp - 16]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 64], rax
    mov qword [rbp - 24], 0
    mov rax, 0
    mov [rbp - 72], rax
    mov rax, 0
    mov [rbp - 24], rax
.L0:
    mov rax, 1
    mov [rbp - 80], rax
    mov rax, 1
    test rax, rax
    jz .L1
    mov qword [rbp - 32], 0
    mov rax, [rbp - 8]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov [rbp - 96], rax
    mov rax, [rbp - 24]
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    mov [rbp - 112], rax
    mov rax, [rbp - 96]
    push rax
    mov rax, [rbp - 112]
    pop rcx
    add rax, rcx
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    mov [rbp - 32], rax
    mov qword [rbp - 40], 0
    mov rax, 0
    mov [rbp - 40], rax
    mov qword [rbp - 48], 0
    mov rax, [rbp - 32]
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    mov [rbp - 136], rax
    mov rax, [rbp - 136]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov [rbp - 144], rax
    mov rax, [rbp - 144]
    mov rax, [rax]
    mov [rbp - 152], rax
    mov rax, [rbp - 152]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 160], rax
    mov rax, [rbp - 160]
    mov [rbp - 168], rax
    mov rax, 0
    mov [rbp - 176], rax
    mov rax, [rbp - 168]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    sete al
    movzx rax, al
    mov [rbp - 184], rax
    mov rax, [rbp - 184]
    test rax, rax
    jz .L3
    mov rax, [rbp - 24]
    mov [rbp - 192], rax
    mov rax, [rbp - 192]
    mov rsp, rbp
    pop rbp
    ret
.L3:
    mov rax, [rbp - 24]
    mov [rbp - 200], rax
    mov rax, [rbp - 200]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 216], rax
    mov rax, [rbp - 216]
    mov [rbp - 24], rax
    jmp .L0
.L1:
    mov rax, [rbp - 24]
    mov [rbp - 224], rax
    mov rax, [rbp - 224]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 16]
    mov [rbp - 232], rax
    mov rax, [rbp - 232]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 240], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

print:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov qword [rbp - 16], 0
    lea rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov qword [rbp - 24], 0
    mov rax, [rbp - 8]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    push rax
    pop rdi
    call _hy_strlen
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 64], rax
    mov rax, 0
    mov [rbp - 72], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    setg al
    movzx rax, al
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    test rax, rax
    jz .L5
    mov rax, 1
    mov [rbp - 96], rax
    mov rax, [rbp - 8]
    mov [rbp - 104], rax
    mov rax, [rbp - 24]
    mov [rbp - 112], rax
    mov rax, 1
    push rax
    mov rax, [rbp - 104]
    push rax
    mov rax, [rbp - 112]
    push rax
    pop rdx
    pop rsi
    pop rdi
    call sys_write
    mov [rbp - 88], rax
.L5:
    lea rax, [rbp - 16]
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 128], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

println:
    push rbp
    mov rbp, rsp
    sub rsp, 160
    mov [rbp - 8], rdi
    mov qword [rbp - 16], 0
    lea rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov qword [rbp - 24], 0
    mov rax, [rbp - 8]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    push rax
    pop rdi
    call _hy_strlen
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 64], rax
    mov rax, 0
    mov [rbp - 72], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    setg al
    movzx rax, al
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    test rax, rax
    jz .L7
    mov rax, 1
    mov [rbp - 96], rax
    mov rax, [rbp - 8]
    mov [rbp - 104], rax
    mov rax, [rbp - 24]
    mov [rbp - 112], rax
    mov rax, 1
    push rax
    mov rax, [rbp - 104]
    push rax
    mov rax, [rbp - 112]
    push rax
    pop rdx
    pop rsi
    pop rdi
    call sys_write
    mov [rbp - 88], rax
.L7:
    mov rax, 1
    mov [rbp - 128], rax
    lea rax, [rel _str0]
    mov [rbp - 136], rax
    mov rax, 1
    mov [rbp - 144], rax
    mov rax, 1
    push rax
    mov rax, [rbp - 136]
    push rax
    mov rax, 1
    push rax
    pop rdx
    pop rsi
    pop rdi
    call sys_write
    mov [rbp - 120], rax
    lea rax, [rbp - 16]
    mov [rbp - 152], rax
    mov rax, [rbp - 152]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 160], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

eprint:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov qword [rbp - 16], 0
    lea rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov qword [rbp - 24], 0
    mov rax, [rbp - 8]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    push rax
    pop rdi
    call _hy_strlen
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 64], rax
    mov rax, 0
    mov [rbp - 72], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    setg al
    movzx rax, al
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    test rax, rax
    jz .L9
    mov rax, 2
    mov [rbp - 96], rax
    mov rax, [rbp - 8]
    mov [rbp - 104], rax
    mov rax, [rbp - 24]
    mov [rbp - 112], rax
    mov rax, 2
    push rax
    mov rax, [rbp - 104]
    push rax
    mov rax, [rbp - 112]
    push rax
    pop rdx
    pop rsi
    pop rdi
    call sys_write
    mov [rbp - 88], rax
.L9:
    lea rax, [rbp - 16]
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 128], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

eprintln:
    push rbp
    mov rbp, rsp
    sub rsp, 160
    mov [rbp - 8], rdi
    mov qword [rbp - 16], 0
    lea rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov qword [rbp - 24], 0
    mov rax, [rbp - 8]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    push rax
    pop rdi
    call _hy_strlen
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 64], rax
    mov rax, 0
    mov [rbp - 72], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    setg al
    movzx rax, al
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    test rax, rax
    jz .L11
    mov rax, 2
    mov [rbp - 96], rax
    mov rax, [rbp - 8]
    mov [rbp - 104], rax
    mov rax, [rbp - 24]
    mov [rbp - 112], rax
    mov rax, 2
    push rax
    mov rax, [rbp - 104]
    push rax
    mov rax, [rbp - 112]
    push rax
    pop rdx
    pop rsi
    pop rdi
    call sys_write
    mov [rbp - 88], rax
.L11:
    mov rax, 2
    mov [rbp - 128], rax
    lea rax, [rel _str0]
    mov [rbp - 136], rax
    mov rax, 1
    mov [rbp - 144], rax
    mov rax, 2
    push rax
    mov rax, [rbp - 136]
    push rax
    mov rax, 1
    push rax
    pop rdx
    pop rsi
    pop rdi
    call sys_write
    mov [rbp - 120], rax
    lea rax, [rbp - 16]
    mov [rbp - 152], rax
    mov rax, [rbp - 152]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 160], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

_sc3:

        mov rax, rdi
        mov rdi, rsi
        mov rsi, rdx
        mov rdx, rcx
        syscall
        ret
    

_sc_pread:

        mov rax, rdi
        mov rdi, rsi
        mov rsi, rdx
        mov rdx, rcx
        mov r10, r8
        xor r8,  r8
        xor r9,  r9
        syscall
        ret
    

_sc_pwrite:

        mov rax, rdi
        mov rdi, rsi
        mov rsi, rdx
        mov rdx, rcx
        mov r10, r8
        xor r8,  r8
        xor r9,  r9
        syscall
        ret
    

_sc_mmap:

        ; rdi=n, rsi=len, rdx=prot, rcx=flags
        mov rax, rdi
        xor rdi, rdi    ; addr = 0
        mov rsi, rsi    ; size = len (already in rsi)
        mov rdx, rdx    ; prot (already in rdx)
        mov r10, rcx    ; flags
        mov r8,  -1     ; fd = -1
        xor r9,  r9     ; offset = 0
        syscall
        ret
    

sys_write:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov qword [rbp - 32], 0
    lea rax, [rbp - 32]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 48], rax
    mov rax, [rel _SYS_WRITE]
    mov [rbp - 64], rax
    mov rax, [rbp - 8]
    mov [rbp - 72], rax
    mov rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    mov [rbp - 88], rax
    mov rax, [rbp - 24]
    mov [rbp - 96], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 88]
    push rax
    mov rax, [rbp - 96]
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 32]
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 112], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_read:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov qword [rbp - 32], 0
    lea rax, [rbp - 32]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 48], rax
    mov rax, [rel _SYS_READ]
    mov [rbp - 64], rax
    mov rax, [rbp - 8]
    mov [rbp - 72], rax
    mov rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    mov [rbp - 88], rax
    mov rax, [rbp - 24]
    mov [rbp - 96], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 88]
    push rax
    mov rax, [rbp - 96]
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 32]
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 112], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_open:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov qword [rbp - 32], 0
    lea rax, [rbp - 32]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 48], rax
    mov rax, [rel _SYS_OPEN]
    mov [rbp - 64], rax
    mov rax, [rbp - 8]
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    mov [rbp - 80], rax
    mov rax, [rbp - 16]
    mov [rbp - 88], rax
    mov rax, [rbp - 24]
    mov [rbp - 96], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 88]
    push rax
    mov rax, [rbp - 96]
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 32]
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 112], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_close:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rbp - 8], rdi
    mov qword [rbp - 16], 0
    lea rax, [rbp - 16]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 32], rax
    mov rax, [rel _SYS_CLOSE]
    mov [rbp - 48], rax
    mov rax, [rbp - 8]
    mov [rbp - 56], rax
    mov rax, 0
    mov [rbp - 64], rax
    mov rax, 0
    mov [rbp - 72], rax
    mov rax, [rbp - 48]
    push rax
    mov rax, [rbp - 56]
    push rax
    mov rax, 0
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 40], rax
    lea rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 88], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_exit:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rbp - 8], rdi
    mov qword [rbp - 16], 0
    lea rax, [rbp - 16]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 32], rax
    mov rax, [rel _SYS_EXIT]
    mov [rbp - 48], rax
    mov rax, [rbp - 8]
    mov [rbp - 56], rax
    mov rax, 0
    mov [rbp - 64], rax
    mov rax, 0
    mov [rbp - 72], rax
    mov rax, [rbp - 48]
    push rax
    mov rax, [rbp - 56]
    push rax
    mov rax, 0
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 40], rax
    lea rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 88], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_mmap:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rbp - 8], rdi
    mov qword [rbp - 16], 0
    lea rax, [rbp - 16]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 32], rax
    mov rax, [rel _SYS_MMAP]
    mov [rbp - 48], rax
    mov rax, [rbp - 8]
    mov [rbp - 56], rax
    mov rax, 3
    mov [rbp - 64], rax
    mov rax, [rel _MAP_FLAGS]
    mov [rbp - 72], rax
    mov rax, [rbp - 48]
    push rax
    mov rax, [rbp - 56]
    push rax
    mov rax, 3
    push rax
    mov rax, [rbp - 72]
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc_mmap
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 88], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_munmap:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    lea rax, [rbp - 24]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov rax, [rel _SYS_MUNMAP]
    mov [rbp - 56], rax
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 16]
    mov [rbp - 72], rax
    mov rax, 0
    mov [rbp - 80], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 64]
    push rax
    mov rax, [rbp - 72]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 48], rax
    lea rax, [rbp - 24]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 96], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_getcwd:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    lea rax, [rbp - 24]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov rax, [rel _SYS_GETCWD]
    mov [rbp - 56], rax
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov [rbp - 72], rax
    mov rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, 0
    mov [rbp - 88], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 80]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 24]
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 104], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_mkdir:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    lea rax, [rbp - 24]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov rax, [rel _SYS_MKDIR]
    mov [rbp - 56], rax
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov [rbp - 72], rax
    mov rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, 0
    mov [rbp - 88], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 80]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 24]
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 104], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_pread:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov [rbp - 32], rcx
    mov qword [rbp - 40], 0
    lea rax, [rbp - 40]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 56], rax
    mov rax, [rel _SYS_PREAD]
    mov [rbp - 72], rax
    mov rax, [rbp - 8]
    mov [rbp - 80], rax
    mov rax, [rbp - 16]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov [rbp - 96], rax
    mov rax, [rbp - 24]
    mov [rbp - 104], rax
    mov rax, [rbp - 32]
    mov [rbp - 112], rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 96]
    push rax
    mov rax, [rbp - 104]
    push rax
    mov rax, [rbp - 112]
    push rax
    pop r8
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc_pread
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 40]
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 128], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_pwrite:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov [rbp - 32], rcx
    mov qword [rbp - 40], 0
    lea rax, [rbp - 40]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 56], rax
    mov rax, [rel _SYS_PWRITE]
    mov [rbp - 72], rax
    mov rax, [rbp - 8]
    mov [rbp - 80], rax
    mov rax, [rbp - 16]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov [rbp - 96], rax
    mov rax, [rbp - 24]
    mov [rbp - 104], rax
    mov rax, [rbp - 32]
    mov [rbp - 112], rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 96]
    push rax
    mov rax, [rbp - 104]
    push rax
    mov rax, [rbp - 112]
    push rax
    pop r8
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc_pwrite
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 40]
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 128], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_fork:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov qword [rbp - 8], 0
    lea rax, [rbp - 8]
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 24], rax
    mov rax, [rel _SYS_FORK]
    mov [rbp - 40], rax
    mov rax, 0
    mov [rbp - 48], rax
    mov rax, 0
    mov [rbp - 56], rax
    mov rax, 0
    mov [rbp - 64], rax
    mov rax, [rbp - 40]
    push rax
    mov rax, 0
    push rax
    mov rax, 0
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 8]
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 80], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_execve:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov qword [rbp - 32], 0
    lea rax, [rbp - 32]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 48], rax
    mov rax, [rel _SYS_EXECVE]
    mov [rbp - 64], rax
    mov rax, [rbp - 8]
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    mov [rbp - 80], rax
    mov rax, [rbp - 16]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov [rbp - 96], rax
    mov rax, [rbp - 24]
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    mov [rbp - 112], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 96]
    push rax
    mov rax, [rbp - 112]
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 32]
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 128], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_wait4:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov [rbp - 32], rcx
    mov qword [rbp - 40], 0
    lea rax, [rbp - 40]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 56], rax
    mov rax, [rel _SYS_WAIT4]
    mov [rbp - 72], rax
    mov rax, [rbp - 8]
    mov [rbp - 80], rax
    mov rax, [rbp - 16]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov [rbp - 96], rax
    mov rax, [rbp - 32]
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    mov [rbp - 112], rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 96]
    push rax
    mov rax, [rbp - 112]
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 40]
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 128], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_pipe2:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    lea rax, [rbp - 24]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov rax, [rel _SYS_PIPE2]
    mov [rbp - 56], rax
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov [rbp - 72], rax
    mov rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, 0
    mov [rbp - 88], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 72]
    push rax
    mov rax, [rbp - 80]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 24]
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 104], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

sys_dup2:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    lea rax, [rbp - 24]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 40], rax
    mov rax, [rel _SYS_DUP2]
    mov [rbp - 56], rax
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 16]
    mov [rbp - 72], rax
    mov rax, 0
    mov [rbp - 80], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 64]
    push rax
    mov rax, [rbp - 72]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call _sc3
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 24]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 96], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

