; Generated by Hylian compiler (IR backend)
; Source: /tmp/test_nums.hy
bits 64
default rel

; Target: linux
; Assemble: nasm -f elf64 <file>.asm -o <file>.o
; Link:     gcc <file>.o -o <program> -no-pie

extern malloc
extern realloc
extern strlen

section .data

section .text
    global main

main:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov qword [rbp - 8], 0
    mov rax, 4294967296
    mov [rbp - 8], rax
    mov qword [rbp - 16], 0
    mov rax, 4294967295
    mov [rbp - 16], rax
    mov qword [rbp - 24], 0
    mov rax, 4294967295
    mov [rbp - 24], rax
    mov qword [rbp - 32], 0
    mov rax, 1000000
    mov [rbp - 32], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

