; Generated by Hylian compiler (IR backend)
; Source: tests/termina_test.hy
bits 64
default rel

; Target: linux
; Assemble: nasm -f elf64 <file>.asm -o <file>.o
; Link:     gcc <file>.o -o <program> -no-pie

extern malloc
extern realloc
extern strlen
extern arena_init
extern arena_alloc
extern arena_free

section .data
    _str0: db "Hello from Termina!", 0
    _str0_len: equ 19

section .text
    global main

main:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov qword [rbp - 8], 0
    lea rax, [rbp - 8]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 48], rax
    lea rdi, [rel _str0]
    mov rsi, 19
    call hylian_println
    mov qword [rbp - 16], 0
    mov rax, 42
    mov [rbp - 16], rax
    mov qword [rbp - 24], 0
    mov rax, 10
    mov [rbp - 24], rax
    mov qword [rbp - 32], 0
    mov rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, [rbp - 24]
    mov [rbp - 88], rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 88]
    pop rcx
    add rax, rcx
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    mov [rbp - 32], rax
    mov rax, 0
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rbp - 8]
    mov [rbp - 112], rax
    mov rax, [rbp - 112]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 120], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

