; Generated by Hylian compiler (IR backend)
; Source: /tmp/t124.hy
bits 64
default rel

; Target: linux
; Assemble: nasm -f elf64 <file>.asm -o <file>.o
;          # prefer pre-built: runtime/std/io.o
;          # fallback:         gcc -O2 -c runtime/std/io.c -o io.o
; Link:     gcc <file>.o io.o -o <program> -no-pie

extern malloc
extern realloc
extern strlen
extern hylian_print
extern hylian_println
extern hylian_int_to_str

section .data

section .text
    global main

main:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov qword [rbp - 8], 0
    ; array literal (3 elements)
    mov rdi, 80
    call malloc
    push r11
    mov r11, rax
    mov qword [r11 + 0], 3
    mov qword [r11 + 8], 8
    mov rax, 10
    mov [r11 + 16], rax
    mov rax, 20
    mov [r11 + 24], rax
    mov rax, 30
    mov [r11 + 32], rax
    mov rax, r11
    pop r11
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov [rbp - 8], rax
    mov rax, [rbp - 8]
    mov [rbp - 56], rax
    mov rax, [rbp - 8]
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    mov rax, [rax + 0]
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov rax, 0
    mov rsp, rbp
    pop rbp
    ret

