; Generated by Hylian compiler (IR backend)
; Source: tests/kernel_features_test.hy
bits 64
default rel

; Target: linux
; Assemble: nasm -f elf64 <file>.asm -o <file>.o
; Link:     ld -T kernel.ld <file>.o -o kernel.elf
;
; Minimal linker script (kernel.ld):
;   ENTRY(_start)
;   SECTIONS {
;     . = 0x100000;
;     .text : { *(.text) }
;     .data : { *(.data) }
;     .bss  : { *(.bss) }
;   }
;          # prefer pre-built: runtime/std/platform/kernel.o
;          # fallback:         gcc -O2 -c runtime/std/platform/kernel.c -o kernel.o

extern malloc
extern realloc
extern strlen
extern hylian_vga_clear
extern hylian_vga_set_color
extern hylian_outb
extern hylian_inb
extern hylian_halt
extern hylian_print
extern hylian_println
extern hylian_int_to_str

section .data
    _str0: db "KERNEL PANIC:", 0
    _str0_len: equ 13
    _str1: db "==============================", 0
    _str1_len: equ 30
    _str2: db "   Hylian Kernel  v0.1.0     ", 0
    _str2_len: equ 29
    _str3: db "   Bare-metal x86-64          ", 0
    _str3_len: equ 30
    _str4: db "colour ", 0
    _str4_len: equ 7
    _str5: db 0x00, 0
    _str5_len: equ 0
    _str6: db "ticks (expect 3): ", 0
    _str6_len: equ 18
    _str7: db "kmin(3,7): ", 0
    _str7_len: equ 11
    _str8: db "kmax(3,7): ", 0
    _str8_len: equ 11
    _str9: db "kabs(-99): ", 0
    _str9_len: equ 11
    _str10: db "sum 1..10: ", 0
    _str10_len: equ 11
    _str11: db "clamp(300,0,255): ", 0
    _str11_len: equ 18
    _str12: db "clamp(-1,0,255): ", 0
    _str12_len: equ 17
    _str13: db "2^10: ", 0
    _str13_len: equ 6
    _str14: db "div_ceil(7,2): ", 0
    _str14_len: equ 15
    _str15: db "div_ceil(8,2): ", 0
    _str15_len: equ 15
    _str16: db "kbd status (port 100): ", 0
    _str16_len: equ 23
    _str17: db "serial_ready: ", 0
    _str17_len: equ 14
    _str18: db "ticks (expect 5): ", 0
    _str18_len: equ 18
    _str19: db "ticks (expect 15): ", 0
    _str19_len: equ 19
    _str20: db "All kernel tests passed.", 0
    _str20_len: equ 24
    _str21: db "Halting CPU.", 0
    _str21_len: equ 12
    kernel_tick: dq 0
    serial_ready: dq 0

section .text
    global _start

tick_increment:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov rax, [rel kernel_tick]
    mov [rbp - 8], rax
    mov rax, 1
    mov [rbp - 16], rax
    mov rax, [rbp - 8]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rel kernel_tick], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

tick_get:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov rax, [rel kernel_tick]
    mov [rbp - 8], rax
    mov rax, [rbp - 8]
    mov rsp, rbp
    pop rbp
    ret

kmin:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rax, [rbp - 24]
    push rax
    mov rax, [rbp - 32]
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    test rax, rax
    jz .L1
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov rsp, rbp
    pop rbp
    ret
.L1:
    mov rax, [rbp - 16]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret

kmax:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rax, [rbp - 24]
    push rax
    mov rax, [rbp - 32]
    pop rcx
    cmp rcx, rax
    setg al
    movzx rax, al
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    test rax, rax
    jz .L3
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov rsp, rbp
    pop rbp
    ret
.L3:
    mov rax, [rbp - 16]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret

kabs:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov [rbp - 16], rax
    mov rax, 0
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    test rax, rax
    jz .L5
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rcx, 0
    mov rax, [rbp - 48]
    sub rcx, rax
    mov rax, rcx
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret
.L5:
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov rsp, rbp
    pop rbp
    ret

sum_range:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, 0
    mov [rbp - 24], rax
    mov qword [rbp - 32], 0
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov [rbp - 32], rax
.L6:
    mov rax, [rbp - 32]
    mov [rbp - 56], rax
    mov rax, [rbp - 16]
    mov [rbp - 64], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 64]
    pop rcx
    cmp rcx, rax
    setle al
    movzx rax, al
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    test rax, rax
    jz .L7
    mov rax, [rbp - 24]
    mov [rbp - 80], rax
    mov rax, [rbp - 32]
    mov [rbp - 88], rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 88]
    pop rcx
    add rax, rcx
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    mov [rbp - 24], rax
    mov rax, [rbp - 32]
    mov [rbp - 104], rax
    mov rax, 1
    mov [rbp - 112], rax
    mov rax, [rbp - 104]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    mov [rbp - 32], rax
    jmp .L6
.L7:
    mov rax, [rbp - 24]
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    mov rsp, rbp
    pop rbp
    ret

clamp:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov rax, [rbp - 8]
    mov [rbp - 32], rax
    mov rax, [rbp - 16]
    mov [rbp - 40], rax
    mov rax, [rbp - 32]
    push rax
    mov rax, [rbp - 40]
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    test rax, rax
    jz .L9
    mov rax, [rbp - 16]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret
.L9:
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 24]
    mov [rbp - 72], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, [rbp - 72]
    pop rcx
    cmp rcx, rax
    setg al
    movzx rax, al
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    test rax, rax
    jz .L11
    mov rax, [rbp - 24]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov rsp, rbp
    pop rbp
    ret
.L11:
    mov rax, [rbp - 8]
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    mov rsp, rbp
    pop rbp
    ret

ipow:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    mov rax, 1
    mov [rbp - 40], rax
    mov rax, 1
    mov [rbp - 24], rax
    mov qword [rbp - 32], 0
    mov rax, 0
    mov [rbp - 48], rax
    mov rax, 0
    mov [rbp - 32], rax
.L12:
    mov rax, [rbp - 32]
    mov [rbp - 56], rax
    mov rax, [rbp - 16]
    mov [rbp - 64], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 64]
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    test rax, rax
    jz .L13
    mov rax, [rbp - 24]
    mov [rbp - 80], rax
    mov rax, [rbp - 8]
    mov [rbp - 88], rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 88]
    pop rcx
    imul rax, rcx
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    mov [rbp - 24], rax
    mov rax, [rbp - 32]
    mov [rbp - 104], rax
    mov rax, 1
    mov [rbp - 112], rax
    mov rax, [rbp - 104]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    mov [rbp - 32], rax
    jmp .L12
.L13:
    mov rax, [rbp - 24]
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    mov rsp, rbp
    pop rbp
    ret

div_ceil:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rax, [rbp - 24]
    push rax
    mov rax, [rbp - 32]
    pop rcx
    add rax, rcx
    mov [rbp - 40], rax
    mov rax, 1
    mov [rbp - 48], rax
    mov rcx, [rbp - 40]
    mov rax, 1
    sub rcx, rax
    mov rax, rcx
    mov [rbp - 56], rax
    mov rax, [rbp - 16]
    mov [rbp - 64], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 64]
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    mov rsp, rbp
    pop rbp
    ret

serial_init:
    push rbp
    mov rbp, rsp
    sub rsp, 176
    mov rax, 1017
    mov [rbp - 16], rax
    mov rax, 0
    mov [rbp - 24], rax
    mov rax, 1017
    push rax
    mov rax, 0
    push rax
    pop rsi
    pop rdi
    call hylian_outb
    mov [rbp - 8], rax
    mov rax, 1019
    mov [rbp - 40], rax
    mov rax, 128
    mov [rbp - 48], rax
    mov rax, 1019
    push rax
    mov rax, 128
    push rax
    pop rsi
    pop rdi
    call hylian_outb
    mov [rbp - 32], rax
    mov rax, 1016
    mov [rbp - 64], rax
    mov rax, 3
    mov [rbp - 72], rax
    mov rax, 1016
    push rax
    mov rax, 3
    push rax
    pop rsi
    pop rdi
    call hylian_outb
    mov [rbp - 56], rax
    mov rax, 1017
    mov [rbp - 88], rax
    mov rax, 0
    mov [rbp - 96], rax
    mov rax, 1017
    push rax
    mov rax, 0
    push rax
    pop rsi
    pop rdi
    call hylian_outb
    mov [rbp - 80], rax
    mov rax, 3
    mov [rbp - 120], rax
    mov rax, 1019
    push rax
    mov rax, 3
    push rax
    pop rsi
    pop rdi
    call hylian_outb
    mov [rbp - 104], rax
    mov rax, 1018
    mov [rbp - 136], rax
    mov rax, 1018
    push rax
    mov rax, 199
    push rax
    pop rsi
    pop rdi
    call hylian_outb
    mov [rbp - 128], rax
    mov rax, 1020
    mov [rbp - 160], rax
    mov rax, 1020
    push rax
    mov rax, 11
    push rax
    pop rsi
    pop rdi
    call hylian_outb
    mov [rbp - 152], rax
    mov rax, 1
    mov [rbp - 176], rax
    mov rax, 1
    mov [rel serial_ready], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

serial_putchar:
    push rbp
    mov rbp, rsp
    sub rsp, 192
    mov [rbp - 8], rdi
    mov qword [rbp - 16], 0
    mov rax, 1021
    mov [rbp - 40], rax
    mov rax, 1021
    push rax
    pop rdi
    call hylian_inb
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    mov [rbp - 16], rax
    mov qword [rbp - 24], 0
    mov rax, [rbp - 16]
    mov [rbp - 48], rax
    mov rax, 32
    mov [rbp - 56], rax
    mov rax, [rbp - 48]
    push rax
    mov rax, 32
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov [rbp - 64], rax
    mov rax, 2
    mov [rbp - 72], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, 2
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov rax, rdx
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    mov [rbp - 24], rax
.L14:
    mov rax, [rbp - 24]
    mov [rbp - 88], rax
    mov rax, 0
    mov [rbp - 96], rax
    mov rax, [rbp - 88]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    sete al
    movzx rax, al
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    test rax, rax
    jz .L15
    mov rax, 1021
    mov [rbp - 120], rax
    mov rax, 1021
    push rax
    pop rdi
    call hylian_inb
    mov [rbp - 112], rax
    mov rax, [rbp - 112]
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    push rax
    mov rax, 32
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov [rbp - 144], rax
    mov rax, [rbp - 144]
    push rax
    mov rax, 2
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov rax, rdx
    mov [rbp - 160], rax
    mov rax, [rbp - 160]
    mov [rbp - 24], rax
    jmp .L14
.L15:
    mov rax, [rbp - 8]
    mov [rbp - 184], rax
    mov rax, 1016
    push rax
    mov rax, [rbp - 184]
    push rax
    pop rsi
    pop rdi
    call hylian_outb
    mov [rbp - 168], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

kpanic:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov [rbp - 8], rdi
    mov rax, 79
    mov [rbp - 24], rax
    mov rax, 79
    push rax
    pop rdi
    call hylian_vga_set_color
    mov [rbp - 16], rax
    lea rdi, [rel _str0]
    mov rsi, 13
    call hylian_println
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    push rax
    mov rdi, rax
    call strlen
    mov rsi, rax
    pop rdi
    call hylian_println
.L16:
    mov rax, 1
    mov [rbp - 56], rax
    mov rax, 1
    mov [rbp - 64], rax
    mov rax, 1
    mov [rbp - 72], rax
    mov rax, 1
    test rax, rax
    jz .L17
    call hylian_halt
    mov [rbp - 80], rax
    jmp .L16
.L17:
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

print_banner:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    call hylian_vga_clear
    mov [rbp - 8], rax
    mov rax, 11
    mov [rbp - 24], rax
    mov rax, 11
    push rax
    pop rdi
    call hylian_vga_set_color
    mov [rbp - 16], rax
    lea rdi, [rel _str1]
    mov rsi, 30
    call hylian_println
    lea rdi, [rel _str2]
    mov rsi, 29
    call hylian_println
    lea rdi, [rel _str3]
    mov rsi, 30
    call hylian_println
    lea rdi, [rel _str1]
    mov rsi, 30
    call hylian_println
    mov rax, 7
    mov [rbp - 72], rax
    mov rax, 7
    push rax
    pop rdi
    call hylian_vga_set_color
    mov [rbp - 64], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

_start:
    push rbp
    mov rbp, rsp
    sub rsp, 944
    call print_banner
    mov [rbp - 32], rax
    mov qword [rbp - 8], 0
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, 0
    mov [rbp - 8], rax
.L18:
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rax, 8
    mov [rbp - 56], rax
    mov rax, [rbp - 48]
    push rax
    mov rax, 8
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    test rax, rax
    jz .L19
    mov rax, [rbp - 8]
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    push rax
    pop rdi
    call hylian_vga_set_color
    mov [rbp - 72], rax
    lea rdi, [rel _str4]
    mov rsi, 7
    call hylian_print
    mov rax, [rbp - 8]
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov rax, [rbp - 8]
    mov [rbp - 112], rax
    mov rax, 1
    mov [rbp - 120], rax
    mov rax, [rbp - 112]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    mov [rbp - 8], rax
    jmp .L18
.L19:
    mov rax, 7
    mov [rbp - 144], rax
    mov rax, 7
    push rax
    pop rdi
    call hylian_vga_set_color
    mov [rbp - 136], rax
    lea rdi, [rel _str5]
    mov rsi, 0
    call hylian_println
    call tick_increment
    mov [rbp - 160], rax
    call tick_increment
    mov [rbp - 168], rax
    call tick_increment
    mov [rbp - 176], rax
    lea rdi, [rel _str6]
    mov rsi, 18
    call hylian_print
    call tick_get
    mov [rbp - 200], rax
    mov rax, [rbp - 200]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str7]
    mov rsi, 11
    call hylian_print
    mov rax, 3
    push rax
    mov rax, 7
    push rax
    pop rsi
    pop rdi
    call kmin
    mov [rbp - 224], rax
    mov rax, [rbp - 224]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str8]
    mov rsi, 11
    call hylian_print
    mov rax, 3
    push rax
    mov rax, 7
    push rax
    pop rsi
    pop rdi
    call kmax
    mov [rbp - 264], rax
    mov rax, [rbp - 264]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str9]
    mov rsi, 11
    call hylian_print
    mov rax, -99
    push rax
    pop rdi
    call kabs
    mov [rbp - 304], rax
    mov rax, [rbp - 304]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str10]
    mov rsi, 11
    call hylian_print
    mov rax, 1
    push rax
    mov rax, 10
    push rax
    pop rsi
    pop rdi
    call sum_range
    mov [rbp - 352], rax
    mov rax, [rbp - 352]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str11]
    mov rsi, 18
    call hylian_print
    mov rax, 300
    push rax
    mov rax, 0
    push rax
    mov rax, 255
    push rax
    pop rdx
    pop rsi
    pop rdi
    call clamp
    mov [rbp - 392], rax
    mov rax, [rbp - 392]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str12]
    mov rsi, 17
    call hylian_print
    mov rax, -1
    push rax
    mov rax, 0
    push rax
    mov rax, 255
    push rax
    pop rdx
    pop rsi
    pop rdi
    call clamp
    mov [rbp - 440], rax
    mov rax, [rbp - 440]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str13]
    mov rsi, 6
    call hylian_print
    mov rax, 2
    push rax
    mov rax, 10
    push rax
    pop rsi
    pop rdi
    call ipow
    mov [rbp - 504], rax
    mov rax, [rbp - 504]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str14]
    mov rsi, 15
    call hylian_print
    mov rax, 7
    push rax
    mov rax, 2
    push rax
    pop rsi
    pop rdi
    call div_ceil
    mov [rbp - 544], rax
    mov rax, [rbp - 544]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str15]
    mov rsi, 15
    call hylian_print
    mov rax, 8
    push rax
    mov rax, 2
    push rax
    pop rsi
    pop rdi
    call div_ceil
    mov [rbp - 584], rax
    mov rax, [rbp - 584]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov rax, 10
    push rax
    pop rdi
    call hylian_vga_set_color
    mov [rbp - 608], rax
    mov qword [rbp - 16], 0
    mov rax, 100
    push rax
    pop rdi
    call hylian_inb
    mov [rbp - 624], rax
    mov rax, [rbp - 624]
    mov [rbp - 16], rax
    lea rdi, [rel _str16]
    mov rsi, 23
    call hylian_print
    mov rax, [rbp - 16]
    mov [rbp - 656], rax
    mov rax, [rbp - 656]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    call serial_init
    mov [rbp - 664], rax
    lea rdi, [rel _str17]
    mov rsi, 14
    call hylian_print
    mov rax, [rel serial_ready]
    mov [rbp - 688], rax
    mov rax, [rbp - 688]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov rax, 72
    push rax
    pop rdi
    call serial_putchar
    mov [rbp - 696], rax
    mov rax, 105
    push rax
    pop rdi
    call serial_putchar
    mov [rbp - 712], rax
    mov rax, 10
    push rax
    pop rdi
    call serial_putchar
    mov [rbp - 728], rax
    call tick_increment
    mov [rbp - 744], rax
    call tick_increment
    mov [rbp - 752], rax
    lea rdi, [rel _str18]
    mov rsi, 18
    call hylian_print
    call tick_get
    mov [rbp - 776], rax
    mov rax, [rbp - 776]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 24], 0
    mov rax, 0
    mov [rbp - 24], rax
.L20:
    mov rax, [rbp - 24]
    mov [rbp - 792], rax
    mov rax, [rbp - 792]
    push rax
    mov rax, 10
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 808], rax
    mov rax, [rbp - 808]
    test rax, rax
    jz .L21
    call tick_increment
    mov [rbp - 816], rax
    mov rax, [rbp - 24]
    mov [rbp - 824], rax
    mov rax, [rbp - 824]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 840], rax
    mov rax, [rbp - 840]
    mov [rbp - 24], rax
    jmp .L20
.L21:
    lea rdi, [rel _str19]
    mov rsi, 19
    call hylian_print
    call tick_get
    mov [rbp - 864], rax
    mov rax, [rbp - 864]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov rax, 15
    push rax
    pop rdi
    call hylian_vga_set_color
    mov [rbp - 872], rax
    lea rdi, [rel _str20]
    mov rsi, 24
    call hylian_println
    lea rdi, [rel _str21]
    mov rsi, 12
    call hylian_println
    mov rax, 7
    push rax
    pop rdi
    call hylian_vga_set_color
    mov [rbp - 904], rax
.L22:
    mov rax, 1
    test rax, rax
    jz .L23
    call hylian_halt
    mov [rbp - 944], rax
    jmp .L22
.L23:
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

