; Generated by Hylian compiler (IR backend)
; Source: tests/test_intrinsics.hy
bits 64
default rel

; Target: linux
; Assemble: nasm -f elf64 <file>.asm -o <file>.o
; Link:     ld -T kernel.ld <file>.o -o kernel.elf
;
; Minimal linker script (kernel.ld):
;   ENTRY(_start)
;   SECTIONS {
;     . = 0x100000;
;     .text : { *(.text) }
;     .data : { *(.data) }
;     .bss  : { *(.bss) }
;   }

extern malloc
extern realloc
extern strlen

section .data

section .text
    global _start

test_descriptor_tables:
    push rbp
    mov rbp, rsp
    sub rsp, 160
    mov qword [rbp - 8], 0
    lea rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 56], rax
    mov qword [rbp - 16], 0
    mov rax, 4096
    mov [rbp - 16], rax
    mov qword [rbp - 24], 0
    mov rax, 255
    mov [rbp - 72], rax
    mov rax, 255
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov [rbp - 80], rax
    mov rax, [rbp - 24]
    mov [rbp - 88], rax
    mov rax, [rbp - 80]
    mov cx, [rbp - 88]
    sub  rsp, 16
    mov  [rsp + 2], rax
    mov  [rsp], cx
    lgdt [rsp]
    add  rsp, 16
    mov qword [rbp - 32], 0
    mov rax, 8192
    mov [rbp - 104], rax
    mov rax, 8192
    mov [rbp - 32], rax
    mov qword [rbp - 40], 0
    mov rax, 4095
    mov [rbp - 112], rax
    mov rax, 4095
    mov [rbp - 40], rax
    mov rax, [rbp - 32]
    mov [rbp - 120], rax
    mov rax, [rbp - 40]
    mov [rbp - 128], rax
    mov rax, [rbp - 120]
    mov cx, [rbp - 128]
    sub  rsp, 16
    mov  [rsp + 2], rax
    mov  [rsp], cx
    lidt [rsp]
    add  rsp, 16
    lea rax, [rbp - 8]
    mov [rbp - 144], rax
    mov rax, [rbp - 144]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 152], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

test_task_register:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov qword [rbp - 8], 0
    lea rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 32], rax
    mov qword [rbp - 16], 0
    mov rax, 40
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov [rbp - 48], rax
    mov ax, [rbp - 48]
    ltr  ax
    lea rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 72], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

test_tlb_invalidation:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov qword [rbp - 8], 0
    lea rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 32], rax
    mov qword [rbp - 16], 0
    mov rax, 4194304
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    invlpg [rax]
    lea rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 72], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

test_msr_operations:
    push rbp
    mov rbp, rsp
    sub rsp, 144
    mov qword [rbp - 8], 0
    lea rax, [rbp - 8]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 48], rax
    mov qword [rbp - 16], 0
    mov rax, 3221225600
    mov [rbp - 16], rax
    mov qword [rbp - 24], 0
    mov rax, 2305
    mov [rbp - 64], rax
    mov rax, 2305
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov [rbp - 72], rax
    mov rax, [rbp - 24]
    mov [rbp - 80], rax
    mov rcx, [rbp - 72]
    mov rax, [rbp - 80]
    mov  rdx, rax
    shr  rdx, 32
    and  eax, 0xFFFFFFFF
    wrmsr
    mov qword [rbp - 32], 0
    mov rax, [rbp - 16]
    mov [rbp - 96], rax
    mov rcx, [rbp - 96]
    rdmsr
    shl  rdx, 32
    or   rax, rdx
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    mov [rbp - 112], rax
    mov rax, [rbp - 24]
    mov [rbp - 120], rax
    mov rax, [rbp - 112]
    push rax
    mov rax, [rbp - 120]
    pop rcx
    cmp rcx, rax
    sete al
    movzx rax, al
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    test rax, rax
    jz .L1
.L1:
    lea rax, [rbp - 8]
    mov [rbp - 136], rax
    mov rax, [rbp - 136]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 144], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

test_syscall_msrs:
    push rbp
    mov rbp, rsp
    sub rsp, 272
    mov qword [rbp - 8], 0
    lea rax, [rbp - 8]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 64], rax
    mov qword [rbp - 16], 0
    mov rax, 3221225601
    mov [rbp - 16], rax
    mov qword [rbp - 24], 0
    mov rax, 3221225602
    mov [rbp - 80], rax
    mov rax, 3221225602
    mov [rbp - 24], rax
    mov qword [rbp - 32], 0
    mov rax, 3221225604
    mov [rbp - 88], rax
    mov rax, 3221225604
    mov [rbp - 32], rax
    mov qword [rbp - 40], 0
    mov rax, 8
    mov [rbp - 96], rax
    mov rax, 8
    movq xmm0, rax
    cvttsd2si rax, xmm0
    mov [rbp - 104], rax
    mov rax, 32
    mov [rbp - 112], rax
    mov rcx, 32
    mov rax, [rbp - 104]
    shl rax, cl
    mov [rbp - 120], rax
    mov rax, 19
    mov [rbp - 128], rax
    mov rax, 19
    movq xmm0, rax
    cvttsd2si rax, xmm0
    mov [rbp - 136], rax
    mov rax, 48
    mov [rbp - 144], rax
    mov rcx, 48
    mov rax, [rbp - 136]
    shl rax, cl
    mov [rbp - 152], rax
    mov rax, [rbp - 120]
    push rax
    mov rax, [rbp - 152]
    pop rcx
    or rax, rcx
    mov [rbp - 160], rax
    mov rax, [rbp - 160]
    mov [rbp - 40], rax
    mov rax, [rbp - 16]
    mov [rbp - 168], rax
    mov rax, [rbp - 40]
    mov [rbp - 176], rax
    mov rcx, [rbp - 168]
    mov rax, [rbp - 176]
    mov  rdx, rax
    shr  rdx, 32
    and  eax, 0xFFFFFFFF
    wrmsr
    mov qword [rbp - 48], 0
    mov rax, 1048576
    mov [rbp - 48], rax
    mov rax, [rbp - 24]
    mov [rbp - 200], rax
    mov rax, [rbp - 48]
    mov [rbp - 208], rax
    mov rcx, [rbp - 200]
    mov rax, [rbp - 208]
    mov  rdx, rax
    shr  rdx, 32
    and  eax, 0xFFFFFFFF
    wrmsr
    mov rax, [rbp - 32]
    mov [rbp - 224], rax
    mov rax, 512
    movq xmm0, rax
    cvttsd2si rax, xmm0
    mov [rbp - 240], rax
    mov rcx, [rbp - 224]
    mov rax, [rbp - 240]
    mov  rdx, rax
    shr  rdx, 32
    and  eax, 0xFFFFFFFF
    wrmsr
    lea rax, [rbp - 8]
    mov [rbp - 256], rax
    mov rax, [rbp - 256]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 264], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

_start:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov qword [rbp - 8], 0
    lea rax, [rbp - 8]
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    push rax
    pop rdi
    call arena_init
    mov [rbp - 24], rax
    call test_descriptor_tables
    mov [rbp - 32], rax
    call test_task_register
    mov [rbp - 40], rax
    call test_tlb_invalidation
    mov [rbp - 48], rax
    call test_msr_operations
    mov [rbp - 56], rax
    call test_syscall_msrs
    mov [rbp - 64], rax
    lea rax, [rbp - 8]
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    push rax
    pop rdi
    call arena_free
    mov [rbp - 80], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

