; Generated by Hylian compiler (IR backend)
; Source: tests/volatile_test.hy
bits 64
default rel

; Target: linux
; Assemble: nasm -f elf64 <file>.asm -o <file>.o
;          # prefer pre-built: runtime/std/io.o
;          # fallback:         gcc -O2 -c runtime/std/io.c -o io.o
; Link:     gcc <file>.o io.o -o <program> -no-pie

extern malloc
extern realloc
extern strlen
extern hylian_print
extern hylian_println
extern hylian_int_to_str

section .data
    _str0: db "counter (3): ", 0
    _str0_len: equ 13
    _str1: db "accum (42): ", 0
    _str1_len: equ 12
    _str2: db "vga row2 addr: ", 0
    _str2_len: equ 15
    _str3: db "vga base back: ", 0
    _str3_len: equ 15
    _str4: db "sum 1..10: ", 0
    _str4_len: equ 11
    _str5: db "sum 0..100: ", 0
    _str5_len: equ 12
    _str6: db "sum 1..1: ", 0
    _str6_len: equ 10
    _str7: db "sum 5..5: ", 0
    _str7_len: equ 10
    _str8: db "clamp(5,1,10): ", 0
    _str8_len: equ 15
    _str9: db "clamp(-3,0,255): ", 0
    _str9_len: equ 17
    _str10: db "clamp(300,0,255): ", 0
    _str10_len: equ 18
    _str11: db "clamp(0,0,0): ", 0
    _str11_len: equ 14
    _str12: db "2^10: ", 0
    _str12_len: equ 6
    _str13: db "3^5: ", 0
    _str13_len: equ 5
    _str14: db "10^0: ", 0
    _str14_len: equ 6
    _str15: db "gcd(48,18): ", 0
    _str15_len: equ 12
    _str16: db "gcd(100,75): ", 0
    _str16_len: equ 13
    _str17: db "gcd(7,13): ", 0
    _str17_len: equ 11
    _str18: db "fib(0): ", 0
    _str18_len: equ 8
    _str19: db "fib(1): ", 0
    _str19_len: equ 8
    _str20: db "fib(10): ", 0
    _str20_len: equ 9
    _str21: db "fib(20): ", 0
    _str21_len: equ 9
    _str22: db "counter after 5 more: ", 0
    _str22_len: equ 22
    _str23: db "7*8: ", 0
    _str23_len: equ 5
    _str24: db "12*12: ", 0
    _str24_len: equ 7
    _str25: db "100*100: ", 0
    _str25_len: equ 9
    _str26: db "100/7: ", 0
    _str26_len: equ 7
    _str27: db "100%7: ", 0
    _str27_len: equ 7
    _str28: db "255/16: ", 0
    _str28_len: equ 8
    _str29: db "255%16: ", 0
    _str29_len: equ 8
    _str30: db "done", 0
    _str30_len: equ 4
    counter: dq 0
    accum: dq 0

section .text
    global main

counter_inc:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov rax, [rel counter]
    mov [rbp - 8], rax
    mov rax, 1
    mov [rbp - 16], rax
    mov rax, [rbp - 8]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rel counter], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

accum_add:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp - 8], rdi
    mov rax, [rel accum]
    mov [rbp - 16], rax
    mov rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    push rax
    mov rax, [rbp - 24]
    pop rcx
    add rax, rcx
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    mov [rel accum], rax
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

ptr_add:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rax, [rbp - 24]
    push rax
    mov rax, [rbp - 32]
    pop rcx
    add rax, rcx
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    mov rsp, rbp
    pop rbp
    ret

ptr_sub:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rcx, [rbp - 24]
    mov rax, [rbp - 32]
    sub rcx, rax
    mov rax, rcx
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    mov rsp, rbp
    pop rbp
    ret

sum_range:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, 0
    mov [rbp - 24], rax
    mov qword [rbp - 32], 0
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov [rbp - 32], rax
.L0:
    mov rax, [rbp - 32]
    mov [rbp - 56], rax
    mov rax, [rbp - 16]
    mov [rbp - 64], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 64]
    pop rcx
    cmp rcx, rax
    setle al
    movzx rax, al
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    test rax, rax
    jz .L1
    mov rax, [rbp - 24]
    mov [rbp - 80], rax
    mov rax, [rbp - 32]
    mov [rbp - 88], rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 88]
    pop rcx
    add rax, rcx
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    mov [rbp - 24], rax
    mov rax, [rbp - 32]
    mov [rbp - 104], rax
    mov rax, 1
    mov [rbp - 112], rax
    mov rax, [rbp - 104]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    mov [rbp - 32], rax
    jmp .L0
.L1:
    mov rax, [rbp - 24]
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    mov rsp, rbp
    pop rbp
    ret

clamp:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov [rbp - 24], rdx
    mov rax, [rbp - 8]
    mov [rbp - 32], rax
    mov rax, [rbp - 16]
    mov [rbp - 40], rax
    mov rax, [rbp - 32]
    push rax
    mov rax, [rbp - 40]
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    test rax, rax
    jz .L3
    mov rax, [rbp - 16]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret
.L3:
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 24]
    mov [rbp - 72], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, [rbp - 72]
    pop rcx
    cmp rcx, rax
    setg al
    movzx rax, al
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    test rax, rax
    jz .L5
    mov rax, [rbp - 24]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov rsp, rbp
    pop rbp
    ret
.L5:
    mov rax, [rbp - 8]
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    mov rsp, rbp
    pop rbp
    ret

abs_val:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov [rbp - 16], rax
    mov rax, 0
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    test rax, rax
    jz .L7
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rcx, 0
    mov rax, [rbp - 48]
    sub rcx, rax
    mov rax, rcx
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rsp, rbp
    pop rbp
    ret
.L7:
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov rsp, rbp
    pop rbp
    ret

ipow:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov qword [rbp - 24], 0
    mov rax, 1
    mov [rbp - 40], rax
    mov rax, 1
    mov [rbp - 24], rax
    mov qword [rbp - 32], 0
    mov rax, 0
    mov [rbp - 48], rax
    mov rax, 0
    mov [rbp - 32], rax
.L8:
    mov rax, [rbp - 32]
    mov [rbp - 56], rax
    mov rax, [rbp - 16]
    mov [rbp - 64], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, [rbp - 64]
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    test rax, rax
    jz .L9
    mov rax, [rbp - 24]
    mov [rbp - 80], rax
    mov rax, [rbp - 8]
    mov [rbp - 88], rax
    mov rax, [rbp - 80]
    push rax
    mov rax, [rbp - 88]
    pop rcx
    imul rax, rcx
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    mov [rbp - 24], rax
    mov rax, [rbp - 32]
    mov [rbp - 104], rax
    mov rax, 1
    mov [rbp - 112], rax
    mov rax, [rbp - 104]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    mov [rbp - 32], rax
    jmp .L8
.L9:
    mov rax, [rbp - 24]
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    mov rsp, rbp
    pop rbp
    ret

gcd:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
.L10:
    mov rax, [rbp - 16]
    mov [rbp - 32], rax
    mov rax, 0
    mov [rbp - 40], rax
    mov rax, [rbp - 32]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    setne al
    movzx rax, al
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    test rax, rax
    jz .L11
    mov qword [rbp - 24], 0
    mov rax, [rbp - 16]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov [rbp - 24], rax
    mov rax, [rbp - 8]
    mov [rbp - 64], rax
    mov rax, [rbp - 16]
    mov [rbp - 72], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, [rbp - 72]
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov rax, rdx
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    mov [rbp - 16], rax
    mov rax, [rbp - 24]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov [rbp - 8], rax
    jmp .L10
.L11:
    mov rax, [rbp - 8]
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    mov rsp, rbp
    pop rbp
    ret

fib:
    push rbp
    mov rbp, rsp
    sub rsp, 192
    mov [rbp - 8], rdi
    mov rax, [rbp - 8]
    mov [rbp - 48], rax
    mov rax, 1
    mov [rbp - 56], rax
    mov rax, [rbp - 48]
    push rax
    mov rax, 1
    pop rcx
    cmp rcx, rax
    setle al
    movzx rax, al
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    test rax, rax
    jz .L13
    mov rax, [rbp - 8]
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    mov rsp, rbp
    pop rbp
    ret
.L13:
    mov qword [rbp - 16], 0
    mov rax, 0
    mov [rbp - 80], rax
    mov rax, 0
    mov [rbp - 16], rax
    mov qword [rbp - 24], 0
    mov rax, 1
    mov [rbp - 88], rax
    mov rax, 1
    mov [rbp - 24], rax
    mov qword [rbp - 32], 0
    mov rax, 2
    mov [rbp - 96], rax
    mov rax, 2
    mov [rbp - 32], rax
.L14:
    mov rax, [rbp - 32]
    mov [rbp - 104], rax
    mov rax, [rbp - 8]
    mov [rbp - 112], rax
    mov rax, [rbp - 104]
    push rax
    mov rax, [rbp - 112]
    pop rcx
    cmp rcx, rax
    setle al
    movzx rax, al
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    test rax, rax
    jz .L15
    mov qword [rbp - 40], 0
    mov rax, [rbp - 16]
    mov [rbp - 128], rax
    mov rax, [rbp - 24]
    mov [rbp - 136], rax
    mov rax, [rbp - 128]
    push rax
    mov rax, [rbp - 136]
    pop rcx
    add rax, rcx
    mov [rbp - 144], rax
    mov rax, [rbp - 144]
    mov [rbp - 40], rax
    mov rax, [rbp - 24]
    mov [rbp - 152], rax
    mov rax, [rbp - 152]
    mov [rbp - 16], rax
    mov rax, [rbp - 40]
    mov [rbp - 160], rax
    mov rax, [rbp - 160]
    mov [rbp - 24], rax
    mov rax, [rbp - 32]
    mov [rbp - 168], rax
    mov rax, [rbp - 168]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 184], rax
    mov rax, [rbp - 184]
    mov [rbp - 32], rax
    jmp .L14
.L15:
    mov rax, [rbp - 24]
    mov [rbp - 192], rax
    mov rax, [rbp - 192]
    mov rsp, rbp
    pop rbp
    ret

main:
    push rbp
    mov rbp, rsp
    sub rsp, 2272
    mov qword [rbp - 8], 0
    mov rax, 42
    mov [rbp - 336], rax
    mov rax, 42
    mov [rbp - 8], rax
    mov rax, [rbp - 8]
    mov [rbp - 352], rax
    mov rax, [rbp - 352]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 16], 0
    mov rax, [rbp - 8]
    mov [rbp - 360], rax
    mov rax, 8
    mov [rbp - 368], rax
    mov rax, [rbp - 360]
    push rax
    mov rax, 8
    pop rcx
    add rax, rcx
    mov [rbp - 376], rax
    mov rax, [rbp - 376]
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov [rbp - 392], rax
    mov rax, [rbp - 392]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 24], 0
    mov rax, [rbp - 16]
    mov [rbp - 400], rax
    mov rax, [rbp - 8]
    mov [rbp - 408], rax
    mov rcx, [rbp - 400]
    mov rax, [rbp - 408]
    sub rcx, rax
    mov rax, rcx
    mov [rbp - 416], rax
    mov rax, [rbp - 416]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 432], rax
    mov rax, [rbp - 432]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 32], 0
    mov rax, [rbp - 8]
    mov [rbp - 440], rax
    mov rax, 2
    mov [rbp - 448], rax
    mov rax, [rbp - 440]
    push rax
    mov rax, 2
    pop rcx
    imul rax, rcx
    mov [rbp - 456], rax
    mov rax, [rbp - 456]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    mov [rbp - 472], rax
    mov rax, [rbp - 472]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 40], 0
    mov rax, [rbp - 32]
    mov [rbp - 480], rax
    mov rax, [rbp - 480]
    push rax
    mov rax, 6
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov [rbp - 496], rax
    mov rax, [rbp - 496]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 512], rax
    mov rax, [rbp - 512]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 48], 0
    mov rax, [rbp - 8]
    mov [rbp - 520], rax
    mov rax, [rbp - 520]
    push rax
    mov rax, 5
    mov rcx, rax
    pop rax
    cqo
    idiv rcx
    mov rax, rdx
    mov [rbp - 536], rax
    mov rax, [rbp - 536]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov [rbp - 552], rax
    mov rax, [rbp - 552]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 56], 0
    mov rax, -42
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov [rbp - 592], rax
    mov rax, [rbp - 592]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 64], 0
    mov rax, [rbp - 56]
    mov [rbp - 600], rax
    mov rax, [rbp - 600]
    push rax
    mov rax, 100
    pop rcx
    add rax, rcx
    mov [rbp - 616], rax
    mov rax, [rbp - 616]
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov [rbp - 632], rax
    mov rax, [rbp - 632]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 72], 0
    mov rax, [rbp - 56]
    mov [rbp - 648], rax
    mov rax, [rbp - 648]
    push rax
    pop rdi
    call abs_val
    mov [rbp - 640], rax
    mov rax, [rbp - 640]
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    mov [rbp - 664], rax
    mov rax, [rbp - 664]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 80], 0
    mov rax, [rbp - 64]
    mov [rbp - 680], rax
    mov rax, [rbp - 680]
    push rax
    pop rdi
    call abs_val
    mov [rbp - 672], rax
    mov rax, [rbp - 672]
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    mov [rbp - 696], rax
    mov rax, [rbp - 696]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 88], 0
    mov rax, 0
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov [rbp - 720], rax
    mov rax, [rbp - 720]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    call counter_inc
    mov [rbp - 728], rax
    call counter_inc
    mov [rbp - 736], rax
    call counter_inc
    mov [rbp - 744], rax
    lea rdi, [rel _str0]
    mov rsi, 13
    call hylian_print
    mov rax, [rel counter]
    mov [rbp - 768], rax
    mov rax, [rbp - 768]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov rax, 10
    push rax
    pop rdi
    call accum_add
    mov [rbp - 776], rax
    mov rax, 20
    push rax
    pop rdi
    call accum_add
    mov [rbp - 792], rax
    mov rax, 12
    push rax
    pop rdi
    call accum_add
    mov [rbp - 808], rax
    lea rdi, [rel _str1]
    mov rsi, 12
    call hylian_print
    mov rax, [rel accum]
    mov [rbp - 840], rax
    mov rax, [rbp - 840]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 96], 0
    mov rax, 753664
    mov [rbp - 96], rax
    mov qword [rbp - 104], 0
    mov rax, 160
    mov [rbp - 104], rax
    mov qword [rbp - 112], 0
    mov rax, [rbp - 96]
    mov [rbp - 872], rax
    mov rax, [rbp - 104]
    mov [rbp - 880], rax
    mov rax, [rbp - 872]
    push rax
    mov rax, [rbp - 880]
    push rax
    pop rsi
    pop rdi
    call ptr_add
    mov [rbp - 864], rax
    mov rax, [rbp - 864]
    mov [rbp - 112], rax
    lea rdi, [rel _str2]
    mov rsi, 15
    call hylian_print
    mov rax, [rbp - 112]
    mov [rbp - 904], rax
    mov rax, [rbp - 904]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 120], 0
    mov rax, [rbp - 112]
    mov [rbp - 920], rax
    mov rax, [rbp - 104]
    mov [rbp - 928], rax
    mov rax, [rbp - 920]
    push rax
    mov rax, [rbp - 928]
    push rax
    pop rsi
    pop rdi
    call ptr_sub
    mov [rbp - 912], rax
    mov rax, [rbp - 912]
    mov [rbp - 120], rax
    lea rdi, [rel _str3]
    mov rsi, 15
    call hylian_print
    mov rax, [rbp - 120]
    mov [rbp - 952], rax
    mov rax, [rbp - 952]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 128], 0
    mov rax, 1
    push rax
    mov rax, 10
    push rax
    pop rsi
    pop rdi
    call sum_range
    mov [rbp - 960], rax
    mov rax, [rbp - 960]
    mov [rbp - 128], rax
    lea rdi, [rel _str4]
    mov rsi, 11
    call hylian_print
    mov rax, [rbp - 128]
    mov [rbp - 1000], rax
    mov rax, [rbp - 1000]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 136], 0
    mov rax, 0
    push rax
    mov rax, 100
    push rax
    pop rsi
    pop rdi
    call sum_range
    mov [rbp - 1008], rax
    mov rax, [rbp - 1008]
    mov [rbp - 136], rax
    lea rdi, [rel _str5]
    mov rsi, 12
    call hylian_print
    mov rax, [rbp - 136]
    mov [rbp - 1048], rax
    mov rax, [rbp - 1048]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 144], 0
    mov rax, 1
    push rax
    mov rax, 1
    push rax
    pop rsi
    pop rdi
    call sum_range
    mov [rbp - 1056], rax
    mov rax, [rbp - 1056]
    mov [rbp - 144], rax
    lea rdi, [rel _str6]
    mov rsi, 10
    call hylian_print
    mov rax, [rbp - 144]
    mov [rbp - 1096], rax
    mov rax, [rbp - 1096]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 152], 0
    mov rax, 5
    push rax
    mov rax, 5
    push rax
    pop rsi
    pop rdi
    call sum_range
    mov [rbp - 1104], rax
    mov rax, [rbp - 1104]
    mov [rbp - 152], rax
    lea rdi, [rel _str7]
    mov rsi, 10
    call hylian_print
    mov rax, [rbp - 152]
    mov [rbp - 1144], rax
    mov rax, [rbp - 1144]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 160], 0
    mov rax, 5
    push rax
    mov rax, 1
    push rax
    mov rax, 10
    push rax
    pop rdx
    pop rsi
    pop rdi
    call clamp
    mov [rbp - 1152], rax
    mov rax, [rbp - 1152]
    mov [rbp - 160], rax
    lea rdi, [rel _str8]
    mov rsi, 15
    call hylian_print
    mov rax, [rbp - 160]
    mov [rbp - 1200], rax
    mov rax, [rbp - 1200]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 168], 0
    mov rax, -3
    push rax
    mov rax, 0
    push rax
    mov rax, 255
    push rax
    pop rdx
    pop rsi
    pop rdi
    call clamp
    mov [rbp - 1208], rax
    mov rax, [rbp - 1208]
    mov [rbp - 168], rax
    lea rdi, [rel _str9]
    mov rsi, 17
    call hylian_print
    mov rax, [rbp - 168]
    mov [rbp - 1272], rax
    mov rax, [rbp - 1272]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 176], 0
    mov rax, 300
    push rax
    mov rax, 0
    push rax
    mov rax, 255
    push rax
    pop rdx
    pop rsi
    pop rdi
    call clamp
    mov [rbp - 1280], rax
    mov rax, [rbp - 1280]
    mov [rbp - 176], rax
    lea rdi, [rel _str10]
    mov rsi, 18
    call hylian_print
    mov rax, [rbp - 176]
    mov [rbp - 1328], rax
    mov rax, [rbp - 1328]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 184], 0
    mov rax, 0
    push rax
    mov rax, 0
    push rax
    mov rax, 0
    push rax
    pop rdx
    pop rsi
    pop rdi
    call clamp
    mov [rbp - 1336], rax
    mov rax, [rbp - 1336]
    mov [rbp - 184], rax
    lea rdi, [rel _str11]
    mov rsi, 14
    call hylian_print
    mov rax, [rbp - 184]
    mov [rbp - 1384], rax
    mov rax, [rbp - 1384]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 192], 0
    mov rax, 2
    push rax
    mov rax, 10
    push rax
    pop rsi
    pop rdi
    call ipow
    mov [rbp - 1392], rax
    mov rax, [rbp - 1392]
    mov [rbp - 192], rax
    lea rdi, [rel _str12]
    mov rsi, 6
    call hylian_print
    mov rax, [rbp - 192]
    mov [rbp - 1432], rax
    mov rax, [rbp - 1432]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 200], 0
    mov rax, 3
    push rax
    mov rax, 5
    push rax
    pop rsi
    pop rdi
    call ipow
    mov [rbp - 1440], rax
    mov rax, [rbp - 1440]
    mov [rbp - 200], rax
    lea rdi, [rel _str13]
    mov rsi, 5
    call hylian_print
    mov rax, [rbp - 200]
    mov [rbp - 1480], rax
    mov rax, [rbp - 1480]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 208], 0
    mov rax, 10
    push rax
    mov rax, 0
    push rax
    pop rsi
    pop rdi
    call ipow
    mov [rbp - 1488], rax
    mov rax, [rbp - 1488]
    mov [rbp - 208], rax
    lea rdi, [rel _str14]
    mov rsi, 6
    call hylian_print
    mov rax, [rbp - 208]
    mov [rbp - 1528], rax
    mov rax, [rbp - 1528]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 216], 0
    mov rax, 48
    push rax
    mov rax, 18
    push rax
    pop rsi
    pop rdi
    call gcd
    mov [rbp - 1536], rax
    mov rax, [rbp - 1536]
    mov [rbp - 216], rax
    lea rdi, [rel _str15]
    mov rsi, 12
    call hylian_print
    mov rax, [rbp - 216]
    mov [rbp - 1576], rax
    mov rax, [rbp - 1576]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 224], 0
    mov rax, 100
    push rax
    mov rax, 75
    push rax
    pop rsi
    pop rdi
    call gcd
    mov [rbp - 1584], rax
    mov rax, [rbp - 1584]
    mov [rbp - 224], rax
    lea rdi, [rel _str16]
    mov rsi, 13
    call hylian_print
    mov rax, [rbp - 224]
    mov [rbp - 1624], rax
    mov rax, [rbp - 1624]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 232], 0
    mov rax, 7
    push rax
    mov rax, 13
    push rax
    pop rsi
    pop rdi
    call gcd
    mov [rbp - 1632], rax
    mov rax, [rbp - 1632]
    mov [rbp - 232], rax
    lea rdi, [rel _str17]
    mov rsi, 11
    call hylian_print
    mov rax, [rbp - 232]
    mov [rbp - 1672], rax
    mov rax, [rbp - 1672]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 240], 0
    mov rax, 0
    push rax
    pop rdi
    call fib
    mov [rbp - 1680], rax
    mov rax, [rbp - 1680]
    mov [rbp - 240], rax
    lea rdi, [rel _str18]
    mov rsi, 8
    call hylian_print
    mov rax, [rbp - 240]
    mov [rbp - 1712], rax
    mov rax, [rbp - 1712]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 248], 0
    mov rax, 1
    push rax
    pop rdi
    call fib
    mov [rbp - 1720], rax
    mov rax, [rbp - 1720]
    mov [rbp - 248], rax
    lea rdi, [rel _str19]
    mov rsi, 8
    call hylian_print
    mov rax, [rbp - 248]
    mov [rbp - 1752], rax
    mov rax, [rbp - 1752]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 256], 0
    mov rax, 10
    push rax
    pop rdi
    call fib
    mov [rbp - 1760], rax
    mov rax, [rbp - 1760]
    mov [rbp - 256], rax
    lea rdi, [rel _str20]
    mov rsi, 9
    call hylian_print
    mov rax, [rbp - 256]
    mov [rbp - 1792], rax
    mov rax, [rbp - 1792]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 264], 0
    mov rax, 20
    push rax
    pop rdi
    call fib
    mov [rbp - 1800], rax
    mov rax, [rbp - 1800]
    mov [rbp - 264], rax
    lea rdi, [rel _str21]
    mov rsi, 9
    call hylian_print
    mov rax, [rbp - 264]
    mov [rbp - 1832], rax
    mov rax, [rbp - 1832]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 272], 0
    mov rax, 0
    mov [rbp - 272], rax
.L16:
    mov rax, [rbp - 272]
    mov [rbp - 1848], rax
    mov rax, [rbp - 1848]
    push rax
    mov rax, 5
    pop rcx
    cmp rcx, rax
    setl al
    movzx rax, al
    mov [rbp - 1864], rax
    mov rax, [rbp - 1864]
    test rax, rax
    jz .L17
    call counter_inc
    mov [rbp - 1872], rax
    mov rax, [rbp - 272]
    mov [rbp - 1880], rax
    mov rax, [rbp - 1880]
    push rax
    mov rax, 1
    pop rcx
    add rax, rcx
    mov [rbp - 1896], rax
    mov rax, [rbp - 1896]
    mov [rbp - 272], rax
    jmp .L16
.L17:
    lea rdi, [rel _str22]
    mov rsi, 22
    call hylian_print
    mov rax, [rel counter]
    mov [rbp - 1920], rax
    mov rax, [rbp - 1920]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 280], 0
    mov rax, 56
    mov [rbp - 280], rax
    lea rdi, [rel _str23]
    mov rsi, 5
    call hylian_print
    mov rax, [rbp - 280]
    mov [rbp - 1968], rax
    mov rax, [rbp - 1968]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 288], 0
    mov rax, 144
    mov [rbp - 288], rax
    lea rdi, [rel _str24]
    mov rsi, 7
    call hylian_print
    mov rax, [rbp - 288]
    mov [rbp - 2016], rax
    mov rax, [rbp - 2016]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 296], 0
    mov rax, 10000
    mov [rbp - 296], rax
    lea rdi, [rel _str25]
    mov rsi, 9
    call hylian_print
    mov rax, [rbp - 296]
    mov [rbp - 2064], rax
    mov rax, [rbp - 2064]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 304], 0
    mov rax, 14
    mov [rbp - 304], rax
    lea rdi, [rel _str26]
    mov rsi, 7
    call hylian_print
    mov rax, [rbp - 304]
    mov [rbp - 2112], rax
    mov rax, [rbp - 2112]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 312], 0
    mov rax, 2
    mov [rbp - 312], rax
    lea rdi, [rel _str27]
    mov rsi, 7
    call hylian_print
    mov rax, [rbp - 312]
    mov [rbp - 2160], rax
    mov rax, [rbp - 2160]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 320], 0
    mov rax, 15
    mov [rbp - 320], rax
    lea rdi, [rel _str28]
    mov rsi, 8
    call hylian_print
    mov rax, [rbp - 320]
    mov [rbp - 2208], rax
    mov rax, [rbp - 2208]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    mov qword [rbp - 328], 0
    mov rax, 15
    mov [rbp - 328], rax
    lea rdi, [rel _str29]
    mov rsi, 8
    call hylian_print
    mov rax, [rbp - 328]
    mov [rbp - 2256], rax
    mov rax, [rbp - 2256]
    sub rsp, 32
    mov rdi, rax
    mov rsi, rsp
    mov rdx, 32
    call hylian_int_to_str
    mov rsi, rax
    mov rdi, rsp
    call hylian_println
    add rsp, 32
    lea rdi, [rel _str30]
    mov rsi, 4
    call hylian_println
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

