id = "hylian"
name = "Hylian"
version = "0.1.0"
schema_version = 1
authors = ["LinkNavi"]
description = "Hylian language support: syntax highlighting, LSP, and tree-sitter grammar."
languages = ["languages/hylian"]

[lib]
kind = "Rust"
version = "0.3.0"

[grammars.hylian]
repository = "https://github.com/LinkNavi/tree-sitter-hylian"
rev = "e164c26d2023d65ab0fb081857ae34d1db18fe70"

[language_servers.hylian-lsp]
language = "Hylian"
languages = []
