#include "lsp_c_extractor.h"
#include <tree_sitter/api.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

/* Generated by tree-sitter-c */
extern const TSLanguage *tree_sitter_c(void);

typedef struct {
    const char *start;
    size_t len;
} Slice;

static Slice node_text(TSNode n, const char *source) {
    uint32_t start = ts_node_start_byte(n);
    uint32_t end   = ts_node_end_byte(n);
    return (Slice){ source + start, end - start };
}

static void slice_to_str(Slice s, char *buf, size_t bufsz) {
    size_t n = s.len < bufsz - 1 ? s.len : bufsz - 1;
    memcpy(buf, s.start, n);
    buf[n] = '\0';
}

/* ─── Query patterns for C function declarations ───────────────────────────── */

static const char *FUNC_QUERY =
    "(declaration"
    "  type: (_) @ret_type"
    "  declarator: (function_declarator"
    "    declarator: (identifier) @name"
    "    parameters: (parameter_list) @params))";

static const char *FUNC_DEF_QUERY =
    "(function_definition"
    "  type: (_) @ret_type"
    "  declarator: (function_declarator"
    "    declarator: (identifier) @name"
    "    parameters: (parameter_list) @params))";

/* ─── Build detail string: "int64_t hylian_crypto_hash(char *algorithm, ...)" ─ */

static void build_c_detail(TSNode ret_node, TSNode name_node, TSNode params_node,
                           const char *source, char *buf, size_t bufsz)
{
    Slice ret   = node_text(ret_node, source);
    Slice name  = node_text(name_node, source);
    Slice params = node_text(params_node, source);

    /* Normalize whitespace in return type */
    char ret_clean[128];
    slice_to_str(ret, ret_clean, sizeof(ret_clean));

    /* Collapse internal whitespace */
    char *w = ret_clean, *r = ret_clean;
    int in_ws = 0;
    while (*r) {
        if (*r == ' ' || *r == '\t' || *r == '\n') {
            if (!in_ws) { *w++ = ' '; in_ws = 1; }
        } else {
            *w++ = *r; in_ws = 0;
        }
        r++;
    }
    *w = '\0';

    /* Trim trailing space */
    size_t rl = strlen(ret_clean);
    while (rl > 0 && ret_clean[rl-1] == ' ') ret_clean[--rl] = '\0';

    snprintf(buf, bufsz, "%s %.*s %.*s",
             ret_clean,
             (int)name.len, name.start,
             (int)params.len, params.start);
}

/* ─── Build label with module prefix for namespacing ───────────────────────── */

static void build_c_label(const char *module_name, const char *func_name,
                          char *buf, size_t bufsz)
{
    if (module_name && module_name[0]) {
        snprintf(buf, bufsz, "%s.%s", module_name, func_name);
    } else {
        snprintf(buf, bufsz, "%s", func_name);
    }
}

/* ─── Main extraction function ─────────────────────────────────────────────── */

int c_extract_functions(const char *filepath,
                        const char *source,
                        CompletionItem *out, int max_out,
                        const char *module_name)
{
    TSParser *parser = ts_parser_new();
    ts_parser_set_language(parser, tree_sitter_c());

    size_t source_len = strlen(source);
    TSTree *tree = ts_parser_parse_string(parser, NULL, source, source_len);
    if (!tree) {
        ts_parser_delete(parser);
        return -1;
    }

    TSNode root = ts_tree_root_node(tree);
    TSQueryError qerr;
    uint32_t err_off;

    /* Try declarations first, then definitions */
    TSQuery *q = ts_query_new(tree_sitter_c(), FUNC_QUERY,
                              strlen(FUNC_QUERY), &err_off, &qerr);
    if (!q) {
        ts_tree_delete(tree);
        ts_parser_delete(parser);
        return -1;
    }

    TSQueryCursor *cursor = ts_query_cursor_new();
    ts_query_cursor_exec(cursor, q, root);

    TSQueryMatch match;
    int count = 0;

    while (ts_query_cursor_next_match(cursor, &match) && count < max_out) {
        TSNode ret_node = {0}, name_node = {0}, params_node = {0};

        for (uint16_t i = 0; i < match.capture_count; i++) {
            const char *cap_name = ts_query_capture_name_for_id(q, match.captures[i].index, NULL);
            TSNode node = match.captures[i].node;

            if (strcmp(cap_name, "ret_type") == 0) ret_node = node;
            else if (strcmp(cap_name, "name") == 0) name_node = node;
            else if (strcmp(cap_name, "params") == 0) params_node = node;
        }

        if (ts_node_is_null(ret_node) || ts_node_is_null(name_node)) continue;

        Slice name_slice = node_text(name_node, source);
        char func_name[128];
        slice_to_str(name_slice, func_name, sizeof(func_name));

        /* Skip static/internal functions unless you want them */
        Slice ret_slice = node_text(ret_node, source);
        if (strstr(ret_slice.start, "static") &&
            (size_t)(strstr(ret_slice.start, "static") - ret_slice.start) < ret_slice.len)
            continue;

        /* Build completion item */
        CompletionItem *it = &out[count++];
        memset(it, 0, sizeof(*it));

        char label[256];
        build_c_label(module_name, func_name, label, sizeof(label));
        snprintf(it->label, sizeof(it->label), "%s", label);

        char detail[512];
        build_c_detail(ret_node, name_node, params_node, source, detail, sizeof(detail));
        snprintf(it->detail, sizeof(it->detail), "%s", detail);

        char doc[512];
        snprintf(doc, sizeof(doc), "C stdlib function from `%s`", filepath);
        snprintf(it->documentation, sizeof(it->documentation), "%s", doc);

        it->kind = COMPLETE_FUNCTION;
    }

    ts_query_cursor_delete(cursor);
    ts_query_delete(q);
    ts_tree_delete(tree);
    ts_parser_delete(parser);

    return count;
}
