#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <dirent.h>
#include <sys/stat.h>

#include "lsp_analysis.h"
#include "lsp_diag.h"
#include "ast.h"
#include "typecheck.h"

/* ─── Parser interface (generated by Bison/Flex with lsp_yy prefix) ─────────── */

extern int  lsp_yyparse(void);
extern void lsp_yyrestart(FILE *f);
extern int  lsp_yylineno;
extern ProgramNode *root;
extern const char  *lsp_current_file;

/* ─── Hylian keywords ────────────────────────────────────────────────────────── */

static const char *hylian_keywords[] = {
    "if", "else", "while", "for", "in", "return", "new", "nil", "true", "false",
    "break", "continue", "defer", "class", "public", "private",
    "include", "void", "int", "str", "bool", "Error",
    "array", "multi", "any", "match", "unsafe", "const", "static", "extern",
    NULL
};

/* ─── Built-in functions ─────────────────────────────────────────────────────── */

typedef struct { const char *name; const char *detail; } BuiltinFunc;

static const BuiltinFunc hylian_builtins[] = {
    { "print",  "void print(...)"               },
    { "panic",  "void panic(str message)"       },
    { "Err",    "Error Err(str message)"        },
    { "len",    "int len(array<T> arr)"         },
    { "push",   "void push(array<T> arr, T val)" },
    { "pop",    "T pop(array<T> arr)"           },
    { "exit",   "void exit(int code)"           },
    { NULL, NULL }
};

/* ─── Path helpers ───────────────────────────────────────────────────────────── */

/* Return heap-allocated directory portion of path, or "." */
static char *dir_of(const char *path) {
    const char *last = strrchr(path, '/');
    if (!last) return strdup(".");
    int len = (int)(last - path);
    char *dir = malloc(len + 1);
    strncpy(dir, path, len);
    dir[len] = '\0';
    return dir;
}

/* Convert dot-separated module name to a filesystem path.
   e.g. base_dir="/proj", module="Game.Player" -> "/proj/Game/Player.hy" */
static char *module_to_filepath(const char *base_dir, const char *module) {
    int mlen = (int)strlen(module);
    /* replace dots with slashes */
    char *rel = malloc(mlen + 4);
    for (int i = 0; i < mlen; i++)
        rel[i] = (module[i] == '.') ? '/' : module[i];
    strcpy(rel + mlen, ".hy");

    int total = (int)strlen(base_dir) + 1 + (int)strlen(rel) + 1;
    char *full = malloc(total);
    snprintf(full, total, "%s/%s", base_dir, rel);
    free(rel);
    return full;
}

/* Normalise a path: resolve ".." and "." components in place.
   Very simple — just collapses double slashes and obvious ".." segments. */
static void normalise_path(char *path) {
    /* collapse // */
    int len = (int)strlen(path);
    for (int i = 0; i < len - 1; i++) {
        if (path[i] == '/' && path[i+1] == '/') {
            memmove(path + i, path + i + 1, len - i);
            len--; i--;
        }
    }
}

/* ─── Type stringification ───────────────────────────────────────────────────── */

static void type_to_str(Type t, char *buf, int bufsz) {
    if (t.kind == TYPE_ARRAY) {
        if (t.elem_type_count > 0 && t.elem_types && t.elem_types[0].name)
            snprintf(buf, bufsz, "array<%s>", t.elem_types[0].name);
        else
            snprintf(buf, bufsz, "array<unknown>");
    } else if (t.kind == TYPE_MULTI) {
        if (t.is_any)
            snprintf(buf, bufsz, "multi<any>");
        else
            snprintf(buf, bufsz, "multi<...>");
    } else if (t.kind == TYPE_TUPLE) {
        char tmp[256] = "(";
        for (int i = 0; i < t.elem_type_count; i++) {
            char et[64];
            type_to_str(t.elem_types[i], et, sizeof(et));
            if (i > 0) strncat(tmp, ", ", sizeof(tmp) - strlen(tmp) - 1);
            strncat(tmp, et, sizeof(tmp) - strlen(tmp) - 1);
        }
        strncat(tmp, ")", sizeof(tmp) - strlen(tmp) - 1);
        snprintf(buf, bufsz, "%s%s", tmp, t.nullable ? "?" : "");
    } else {
        snprintf(buf, bufsz, "%s%s",
                 t.name ? t.name : "unknown",
                 t.nullable ? "?" : "");
    }
}

/* ─── Completion helpers ─────────────────────────────────────────────────────── */

static void add_completion_to(CompletionItem *arr, int *count, int max,
                               const char *label, CompletionKind kind,
                               const char *detail, const char *doc)
{
    if (*count >= max) return;
    /* Deduplicate: skip if a completion with the same label+kind already exists */
    for (int i = 0; i < *count; i++) {
        if (arr[i].kind == kind && strcmp(arr[i].label, label) == 0)
            return;
    }
    CompletionItem *it = &arr[(*count)++];
    snprintf(it->label,         sizeof(it->label),         "%s", label  ? label  : "");
    snprintf(it->detail,        sizeof(it->detail),        "%s", detail ? detail : "");
    snprintf(it->documentation, sizeof(it->documentation), "%s", doc    ? doc    : "");
    it->kind = kind;
}

/* Build a human-readable signature string for a function/method */
static void build_sig(char *buf, int bufsz,
                      const char *ret, const char *name,
                      ASTNode **params, int param_count)
{
    char pstr[256] = "";
    for (int p = 0; p < param_count && params && params[p]; p++) {
        VarDeclNode *vd = (VarDeclNode *)params[p];
        char pt[32];
        type_to_str(vd->var_type, pt, sizeof(pt));
        if (p > 0) strncat(pstr, ", ", sizeof(pstr) - strlen(pstr) - 1);
        strncat(pstr, pt,           sizeof(pstr) - strlen(pstr) - 1);
        strncat(pstr, " ",          sizeof(pstr) - strlen(pstr) - 1);
        strncat(pstr, vd->var_name, sizeof(pstr) - strlen(pstr) - 1);
    }
    snprintf(buf, bufsz, "%s %s(%s)", ret, name, pstr);
}

/* ─── Parse one source text ──────────────────────────────────────────────────── */

static ProgramNode *parse_source(const char *filepath, const char *source) {
    FILE *tmp = tmpfile();
    if (!tmp) return NULL;
    fwrite(source, 1, strlen(source), tmp);
    rewind(tmp);

    root = NULL;
    lsp_current_file = filepath;
    lsp_yyrestart(tmp);
    lsp_yylineno = 1;
    lsp_yyparse();
    fclose(tmp);

    ProgramNode *prog = root;
    root = NULL;
    return prog;
}

static ProgramNode *parse_file_from_disk(const char *filepath) {
    FILE *f = fopen(filepath, "r");
    if (!f) return NULL;

    /* Read the whole file into memory */
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    rewind(f);
    if (sz <= 0) { fclose(f); return NULL; }

    char *buf = malloc(sz + 1);
    if (!buf) { fclose(f); return NULL; }
    fread(buf, 1, sz, f);
    fclose(f);
    buf[sz] = '\0';

    ProgramNode *prog = parse_source(filepath, buf);
    free(buf);
    return prog;
}

/* ─── Populate completions from one ProgramNode ──────────────────────────────── */

static void index_program(ProgramNode *prog,
                           const char *source_file,
                           CompletionItem *arr, int *count, int max)
{
    if (!prog) return;

    for (int i = 0; i < prog->decl_count; i++) {
        ASTNode *d = prog->declarations[i];
        if (!d) continue;

        if (d->type == NODE_FUNC) {
            FuncNode *fn = (FuncNode *)d;
            char ret[64]; type_to_str(fn->return_type, ret, sizeof(ret));
            char sig[256]; build_sig(sig, sizeof(sig), ret, fn->name,
                                     fn->params, fn->param_count);
            char doc[512];
            snprintf(doc, sizeof(doc), "defined in `%s`", source_file);
            add_completion_to(arr, count, max, fn->name, COMPLETE_FUNCTION, sig, doc);
        }

        if (d->type == NODE_CLASS) {
            ClassNode *cn = (ClassNode *)d;
            char doc[512];
            snprintf(doc, sizeof(doc), "defined in `%s`", source_file);
            add_completion_to(arr, count, max, cn->name, COMPLETE_CLASS,
                              cn->name, doc);

            for (int m = 0; m < cn->method_count; m++) {
                MethodNode *mn = cn->methods[m];
                if (!mn) continue;
                char ret[64]; type_to_str(mn->return_type, ret, sizeof(ret));
                char sig[256];
                char msig[300];
                build_sig(sig, sizeof(sig), ret, mn->name,
                          mn->params, mn->param_count);
                snprintf(msig, sizeof(msig), "%s::%s", cn->name, sig + strlen(ret) + 1);
                char mdoc[512];
                snprintf(mdoc, sizeof(mdoc), "method of `%s` in `%s`",
                         cn->name, source_file);
                add_completion_to(arr, count, max, mn->name, COMPLETE_METHOD,
                                  msig, mdoc);
            }

            for (int f = 0; f < cn->field_count; f++) {
                FieldNode *fld = cn->fields[f];
                if (!fld || !fld->is_public) continue;
                char ft[64]; type_to_str(fld->field_type, ft, sizeof(ft));
                char det[128];
                snprintf(det, sizeof(det), "%s.%s: %s", cn->name, fld->name, ft);
                char fdoc[512];
                snprintf(fdoc, sizeof(fdoc), "field of `%s` in `%s`",
                         cn->name, source_file);
                add_completion_to(arr, count, max, fld->name, COMPLETE_FIELD,
                                  det, fdoc);
            }
        }
    }
}

/* ─── Recursively scan a directory for *.hy files ────────────────────────────── */

static void scan_dir(LspProject *proj, const char *dir_path) {
    DIR *d = opendir(dir_path);
    if (!d) return;

    struct dirent *ent;
    while ((ent = readdir(d)) != NULL) {
        if (ent->d_name[0] == '.') continue; /* skip hidden / . / .. */

        char full[1024];
        snprintf(full, sizeof(full), "%s/%s", dir_path, ent->d_name);
        normalise_path(full);

        struct stat st;
        if (stat(full, &st) != 0) continue;

        if (S_ISDIR(st.st_mode)) {
            scan_dir(proj, full);
        } else if (S_ISREG(st.st_mode)) {
            /* Check for .hy extension */
            int nlen = (int)strlen(ent->d_name);
            if (nlen > 3 && strcmp(ent->d_name + nlen - 3, ".hy") == 0) {
                lsp_project_get_or_add_file(proj, full);
            }
        }
    }
    closedir(d);
}

/* ─── Resolve and index imports for one ProjectFile ─────────────────────────── */

static void resolve_imports(LspProject *proj, ProjectFile *pf) {
    if (!pf->program) return;

    char *file_dir = dir_of(pf->filepath);

    for (int i = 0; i < pf->program->include_count; i++) {
        const char *inc = pf->program->includes[i];

        /* std.* are runtime stubs — skip */
        if (strncmp(inc, "std.", 4) == 0) continue;

        /* Resolve relative to the importing file's directory */
        char *dep_path = module_to_filepath(file_dir, inc);
        normalise_path(dep_path);

        /* If we don't have this file in the index yet, add and parse it */
        ProjectFile *dep = lsp_project_find_file(proj, dep_path);
        if (!dep) {
            dep = lsp_project_get_or_add_file(proj, dep_path);
            if (dep && !dep->program) {
                /* Parse from disk — capture diagnostics into dep's own buffer */
                LspDiag saved[LSP_DIAG_MAX];
                int saved_count = lsp_diag_count;
                memcpy(saved, lsp_diags, saved_count * sizeof(LspDiag));
                lsp_diag_clear();

                dep->program = parse_file_from_disk(dep_path);

                /* Capture dep's parse diagnostics */
                dep->diag_count = lsp_diag_count < LSP_DIAG_MAX
                                  ? lsp_diag_count : LSP_DIAG_MAX;
                memcpy(dep->diags, lsp_diags,
                       dep->diag_count * sizeof(LspDiag));

                /* Restore the caller's diagnostics */
                lsp_diag_clear();
                memcpy(lsp_diags, saved, saved_count * sizeof(LspDiag));
                lsp_diag_count = saved_count;

                if (dep->program)
                    resolve_imports(proj, dep);
            }
        }

        free(dep_path);
    }

    free(file_dir);
}

/* ═══════════════════════════════════════════════════════════════════════════════
   Project API implementation
   ═══════════════════════════════════════════════════════════════════════════════ */

LspProject *lsp_project_create(const char *root_dir) {
    LspProject *proj = calloc(1, sizeof(LspProject));
    if (!proj) return NULL;

    snprintf(proj->root_dir, sizeof(proj->root_dir), "%s",
             root_dir ? root_dir : ".");

    /* Scan the workspace tree for all .hy files */
    scan_dir(proj, proj->root_dir);

    /* Parse every file we found (errors captured per-file) */
    for (int i = 0; i < proj->file_count; i++) {
        ProjectFile *pf = &proj->files[i];
        if (!pf->program) {
            LspDiag saved[LSP_DIAG_MAX];
            int saved_count = lsp_diag_count;
            memcpy(saved, lsp_diags, saved_count * sizeof(LspDiag));
            lsp_diag_clear();

            pf->program = parse_file_from_disk(pf->filepath);

            pf->diag_count = lsp_diag_count < LSP_DIAG_MAX
                             ? lsp_diag_count : LSP_DIAG_MAX;
            memcpy(pf->diags, lsp_diags, pf->diag_count * sizeof(LspDiag));

            lsp_diag_clear();
            memcpy(lsp_diags, saved, saved_count * sizeof(LspDiag));
            lsp_diag_count = saved_count;
        }
    }

    lsp_project_rebuild_index(proj);
    return proj;
}

void lsp_project_free(LspProject *proj) {
    if (!proj) return;
    for (int i = 0; i < proj->file_count; i++)
        free(proj->files[i].source);
    free(proj);
}

ProjectFile *lsp_project_find_file(LspProject *proj, const char *filepath) {
    for (int i = 0; i < proj->file_count; i++)
        if (strcmp(proj->files[i].filepath, filepath) == 0)
            return &proj->files[i];
    return NULL;
}

ProjectFile *lsp_project_get_or_add_file(LspProject *proj, const char *filepath) {
    ProjectFile *existing = lsp_project_find_file(proj, filepath);
    if (existing) return existing;
    if (proj->file_count >= MAX_PROJECT_FILES) return NULL;
    ProjectFile *pf = &proj->files[proj->file_count++];
    memset(pf, 0, sizeof(*pf));
    snprintf(pf->filepath, sizeof(pf->filepath), "%s", filepath);
    return pf;
}

void lsp_project_update_file(LspProject *proj,
                              const char *filepath,
                              const char *source)
{
    ProjectFile *pf = lsp_project_get_or_add_file(proj, filepath);
    if (!pf) return;

    /* Store the new source text */
    free(pf->source);
    pf->source = strdup(source);
    pf->dirty  = 0;

    /* Re-parse, capturing diagnostics into this file's own buffer */
    lsp_diag_clear();
    pf->program = parse_source(filepath, source);

    /* Run typecheck — also pushes to lsp_diag */
    if (pf->program)
        lsp_typecheck(pf->program, filepath);

    pf->diag_count = lsp_diag_count < LSP_DIAG_MAX
                     ? lsp_diag_count : LSP_DIAG_MAX;
    memcpy(pf->diags, lsp_diags, pf->diag_count * sizeof(LspDiag));

    /* Resolve imports — ensures dependency files are in the index */
    resolve_imports(proj, pf);

    /* Rebuild the merged symbol table */
    lsp_project_rebuild_index(proj);
}

void lsp_project_rebuild_index(LspProject *proj) {
    proj->global_completion_count = 0;

    /* Keywords and builtins first */
    for (int i = 0; hylian_keywords[i]; i++) {
        add_completion_to(proj->global_completions,
                          &proj->global_completion_count, MAX_COMPLETIONS,
                          hylian_keywords[i], COMPLETE_KEYWORD, "keyword", NULL);
    }
    for (int i = 0; hylian_builtins[i].name; i++) {
        add_completion_to(proj->global_completions,
                          &proj->global_completion_count, MAX_COMPLETIONS,
                          hylian_builtins[i].name, COMPLETE_FUNCTION,
                          hylian_builtins[i].detail, "built-in function");
    }

    /* Symbols from every indexed file */
    for (int i = 0; i < proj->file_count; i++) {
        ProjectFile *pf = &proj->files[i];
        if (!pf->program) continue;

        /* Use a short relative label for the "defined in" doc string */
        const char *label = pf->filepath;
        /* Strip root_dir prefix for readability */
        int rlen = (int)strlen(proj->root_dir);
        if (strncmp(pf->filepath, proj->root_dir, rlen) == 0 &&
            pf->filepath[rlen] == '/')
            label = pf->filepath + rlen + 1;

        index_program(pf->program, label,
                      proj->global_completions,
                      &proj->global_completion_count, MAX_COMPLETIONS);
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
   Document API implementation
   ═══════════════════════════════════════════════════════════════════════════════ */

LspState *lsp_analyze(LspProject *proj,
                       const char *filepath,
                       const char *source)
{
    LspState *st = calloc(1, sizeof(LspState));
    if (!st) return NULL;

    st->project = proj;
    snprintf(st->filepath, sizeof(st->filepath), "%s",
             filepath ? filepath : "<unknown>");

    if (source) {
        lsp_project_update_file(proj, filepath, source);
    }

    st->file = lsp_project_find_file(proj, filepath);
    if (!st->file) {
        /* File wasn't in the index yet (e.g. no root_dir set) — add it */
        st->file = lsp_project_get_or_add_file(proj, filepath);
        if (st->file && source) {
            lsp_diag_clear();
            st->file->program = parse_source(filepath, source);
            if (st->file->program)
                lsp_typecheck(st->file->program, filepath);
            st->file->diag_count =
                lsp_diag_count < LSP_DIAG_MAX ? lsp_diag_count : LSP_DIAG_MAX;
            memcpy(st->file->diags, lsp_diags,
                   st->file->diag_count * sizeof(LspDiag));
        }
    }

    return st;
}

void lsp_state_free(LspState *st) {
    free(st);
}

/* ─── Cursor helpers (shared by complete + hover) ────────────────────────────── */

static char *word_at(const char *source, int line, int col) {
    int cur_line = 0;
    const char *p = source;
    while (*p && cur_line < line) { if (*p == '\n') cur_line++; p++; }
    if (cur_line < line) return NULL;

    int cur_col = 0;
    while (*p && *p != '\n' && cur_col < col) { p++; cur_col++; }

    const char *word_end = p;
    while (p > source && (isalnum((unsigned char)*(p-1)) || *(p-1) == '_')) p--;
    const char *word_start = p;
    while (*word_end && (isalnum((unsigned char)*word_end) || *word_end == '_'))
        word_end++;

    int len = (int)(word_end - word_start);
    if (len <= 0) return NULL;
    char *w = malloc(len + 1);
    memcpy(w, word_start, len);
    w[len] = '\0';
    return w;
}

/* Returns 1 if the cursor is immediately after "identifier." and fills
   obj_word_out with the identifier name. */
static int cursor_after_dot(const char *source, int line, int col,
                             char *obj_word_out, int obj_word_sz)
{
    int cur_line = 0;
    const char *p = source;
    while (*p && cur_line < line) { if (*p == '\n') cur_line++; p++; }
    int cur_col = 0;
    const char *line_start = p;
    while (*p && *p != '\n' && cur_col < col) { p++; cur_col++; }

    const char *q = p;
    while (q > line_start && (isalnum((unsigned char)*(q-1)) || *(q-1) == '_')) q--;

    if (q > line_start && *(q-1) == '.') {
        const char *dot    = q - 1;
        const char *obj_end = dot;
        while (obj_end > line_start &&
               (isalnum((unsigned char)*(obj_end-1)) || *(obj_end-1) == '_'))
            obj_end--;
        int len = (int)(dot - obj_end);
        if (len > 0 && obj_word_out) {
            int copy = len < obj_word_sz - 1 ? len : obj_word_sz - 1;
            memcpy(obj_word_out, obj_end, copy);
            obj_word_out[copy] = '\0';
        }
        return 1;
    }
    return 0;
}

/* ─── Find the class name for a variable in a program ───────────────────────── */
/* Searches function parameters and body var decls for `var_name`.
   Returns the type name string (points into AST — do not free), or NULL. */
static const char *resolve_var_type(ProgramNode *prog, const char *var_name) {
    if (!prog) return NULL;
    for (int i = 0; i < prog->decl_count; i++) {
        ASTNode *d = prog->declarations[i];
        if (!d) continue;

        if (d->type == NODE_FUNC) {
            FuncNode *fn = (FuncNode *)d;
            for (int p = 0; p < fn->param_count && fn->params[p]; p++) {
                VarDeclNode *vd = (VarDeclNode *)fn->params[p];
                if (strcmp(vd->var_name, var_name) == 0)
                    return vd->var_type.name;
            }
            for (int b = 0; b < fn->body_count && fn->body[b]; b++) {
                if (fn->body[b]->type == NODE_VAR_DECL) {
                    VarDeclNode *vd = (VarDeclNode *)fn->body[b];
                    if (strcmp(vd->var_name, var_name) == 0)
                        return vd->var_type.name;
                }
            }
        }
        if (d->type == NODE_CLASS) {
            ClassNode *cn = (ClassNode *)d;
            for (int m = 0; m < cn->method_count; m++) {
                MethodNode *mn = cn->methods[m];
                if (!mn) continue;
                for (int p = 0; p < mn->param_count && mn->params[p]; p++) {
                    VarDeclNode *vd = (VarDeclNode *)mn->params[p];
                    if (strcmp(vd->var_name, var_name) == 0)
                        return vd->var_type.name;
                }
                for (int b = 0; b < mn->body_count && mn->body[b]; b++) {
                    if (mn->body[b]->type == NODE_VAR_DECL) {
                        VarDeclNode *vd = (VarDeclNode *)mn->body[b];
                        if (strcmp(vd->var_name, var_name) == 0)
                            return vd->var_type.name;
                    }
                }
            }
        }
    }
    return NULL;
}

/* ─── Find a class node across the whole project ────────────────────────────── */
static ClassNode *find_class_in_project(LspProject *proj, const char *class_name) {
    if (!proj || !class_name) return NULL;
    for (int f = 0; f < proj->file_count; f++) {
        ProgramNode *prog = proj->files[f].program;
        if (!prog) continue;
        for (int i = 0; i < prog->decl_count; i++) {
            ASTNode *d = prog->declarations[i];
            if (d && d->type == NODE_CLASS) {
                ClassNode *cn = (ClassNode *)d;
                if (strcmp(cn->name, class_name) == 0)
                    return cn;
            }
        }
    }
    return NULL;
}

/* ─── Collect local variables reachable at cursor ────────────────────────────── */
static void collect_locals(ProgramNode *prog, int line,
                            CompletionItem *out, int *count, int max)
{
    if (!prog) return;
    (void)line;
    for (int i = 0; i < prog->decl_count; i++) {
        ASTNode *d = prog->declarations[i];
        if (!d) continue;

        if (d->type == NODE_FUNC) {
            FuncNode *fn = (FuncNode *)d;
            for (int p = 0; p < fn->param_count && fn->params[p]; p++) {
                VarDeclNode *vd = (VarDeclNode *)fn->params[p];
                char det[64]; type_to_str(vd->var_type, det, sizeof(det));
                add_completion_to(out, count, max, vd->var_name,
                                  COMPLETE_VARIABLE, det, "parameter");
            }
            for (int b = 0; b < fn->body_count && fn->body[b]; b++) {
                if (fn->body[b]->type == NODE_VAR_DECL) {
                    VarDeclNode *vd = (VarDeclNode *)fn->body[b];
                    char det[64]; type_to_str(vd->var_type, det, sizeof(det));
                    add_completion_to(out, count, max, vd->var_name,
                                      COMPLETE_VARIABLE, det, "local variable");
                }
            }
        }

        if (d->type == NODE_CLASS) {
            ClassNode *cn = (ClassNode *)d;
            add_completion_to(out, count, max, "self",
                              COMPLETE_VARIABLE, cn->name, "implicit self");
            for (int m = 0; m < cn->method_count; m++) {
                MethodNode *mn = cn->methods[m];
                if (!mn) continue;
                for (int p = 0; p < mn->param_count && mn->params[p]; p++) {
                    VarDeclNode *vd = (VarDeclNode *)mn->params[p];
                    char det[64]; type_to_str(vd->var_type, det, sizeof(det));
                    add_completion_to(out, count, max, vd->var_name,
                                      COMPLETE_VARIABLE, det, "parameter");
                }
                for (int b = 0; b < mn->body_count && mn->body[b]; b++) {
                    if (mn->body[b]->type == NODE_VAR_DECL) {
                        VarDeclNode *vd = (VarDeclNode *)mn->body[b];
                        char det[64]; type_to_str(vd->var_type, det, sizeof(det));
                        add_completion_to(out, count, max, vd->var_name,
                                          COMPLETE_VARIABLE, det, "local variable");
                    }
                }
            }
        }
    }
}

/* ─── Include block detection ────────────────────────────────────────────────── */

/* Known stdlib modules */
static const char *stdlib_modules[] = {
    "std.io",
    "std.string",
    "std.errors",
    "std.crypto",
    "std.system.env",
    "std.system.filesystem",
    "std.networking.tcp",
    "std.networking.udp",
    "std.networking.https",
    NULL
};

/* Returns 1 if the cursor (line, col) is inside an unclosed `include { }` block.
   Also fills prefix_out with whatever partial module name is being typed. */
static int cursor_in_include(const char *source, int line, int col,
                              char *prefix_out, int prefix_sz)
{
    if (!source) return 0;

    /* Find the offset of the cursor */
    int cur_line = 0;
    const char *p = source;
    while (*p && cur_line < line) { if (*p++ == '\n') cur_line++; }
    int cur_col = 0;
    while (*p && *p != '\n' && cur_col < col) { p++; cur_col++; }
    const char *cursor = p;

    /* Scan backward looking for `include` followed by `{` with no closing `}` */
    const char *q = cursor;
    int brace_depth = 0;
    while (q > source) {
        q--;
        if (*q == '}') brace_depth++;
        else if (*q == '{') {
            if (brace_depth > 0) { brace_depth--; continue; }
            /* found an unmatched { — check if preceded by `include` */
            const char *r = q - 1;
            while (r >= source && (*r == ' ' || *r == '\t' || *r == '\n' || *r == '\r'))
                r--;
            /* r should point at the last char of "include" */
            if (r - source >= 6 && strncmp(r - 6, "include", 7) == 0 &&
                (r - 6 == source || !isalnum((unsigned char)*(r-7)))) {
                /* We're inside include { ... }. Extract the partial word at cursor. */
                if (prefix_out && prefix_sz > 0) {
                    const char *word_start = cursor;
                    while (word_start > source &&
                           (isalnum((unsigned char)*(word_start-1)) ||
                            *(word_start-1) == '.' || *(word_start-1) == '_'))
                        word_start--;
                    int len = (int)(cursor - word_start);
                    if (len >= prefix_sz) len = prefix_sz - 1;
                    memcpy(prefix_out, word_start, len);
                    prefix_out[len] = '\0';
                }
                return 1;
            }
            break;
        }
    }
    return 0;
}

/* Convert an absolute .hy filepath to a dot-separated module name relative
   to root_dir. e.g. /proj/Game/Player.hy -> "Game.Player" */
static void filepath_to_module(const char *root_dir, const char *filepath,
                               char *buf, int bufsz)
{
    int rlen = (int)strlen(root_dir);
    const char *rel = filepath;
    if (strncmp(filepath, root_dir, rlen) == 0 && filepath[rlen] == '/')
        rel = filepath + rlen + 1;

    int len = (int)strlen(rel);
    /* strip .hy suffix */
    if (len > 3 && strcmp(rel + len - 3, ".hy") == 0)
        len -= 3;

    int copy = len < bufsz - 1 ? len : bufsz - 1;
    for (int i = 0; i < copy; i++)
        buf[i] = (rel[i] == '/') ? '.' : rel[i];
    buf[copy] = '\0';
}

/* ═══════════════════════════════════════════════════════════════════════════════
   Public: lsp_complete
   ═══════════════════════════════════════════════════════════════════════════════ */

int lsp_complete(LspState *st,
                 const char *source, int line, int col,
                 CompletionItem *out, int max_out)
{
    if (!st || !out || max_out <= 0) return 0;

    LspProject *proj = st->project;
    int count = 0;

    /* ── Include block completion ── */
    char inc_prefix[256] = "";
    if (cursor_in_include(source, line, col, inc_prefix, sizeof(inc_prefix))) {
        /* Stdlib modules */
        for (int i = 0; stdlib_modules[i] && count < max_out; i++) {
            if (inc_prefix[0] == '\0' ||
                strncmp(stdlib_modules[i], inc_prefix, strlen(inc_prefix)) == 0) {
                add_completion_to(out, &count, max_out,
                                  stdlib_modules[i], COMPLETE_MODULE,
                                  "stdlib module", NULL);
            }
        }
        /* User project files */
        if (proj) {
            for (int f = 0; f < proj->file_count && count < max_out; f++) {
                char mod[512];
                filepath_to_module(proj->root_dir, proj->files[f].filepath,
                                   mod, sizeof(mod));
                if (mod[0] == '\0') continue;
                /* skip std.* paths that ended up here */
                if (strncmp(mod, "std.", 4) == 0) continue;
                if (inc_prefix[0] == '\0' ||
                    strncmp(mod, inc_prefix, strlen(inc_prefix)) == 0) {
                    add_completion_to(out, &count, max_out,
                                      mod, COMPLETE_MODULE,
                                      "project file", NULL);
                }
            }
        }
        return count;
    }

    /* ── Member access completion (after a '.') ── */
    char obj_name[128] = "";
    if (cursor_after_dot(source, line, col, obj_name, sizeof(obj_name))
        && obj_name[0])
    {
        /* Resolve the type of obj_name from the current file first,
           then from the rest of the project. */
        const char *class_name = NULL;

        /* Check current file */
        ProgramNode *cur_prog = st->file ? st->file->program : NULL;
        if (cur_prog)
            class_name = resolve_var_type(cur_prog, obj_name);

        /* Check other project files if not found */
        if (!class_name && proj) {
            for (int f = 0; f < proj->file_count && !class_name; f++) {
                if (st->file && &proj->files[f] == st->file) continue;
                class_name = resolve_var_type(proj->files[f].program, obj_name);
            }
        }

        if (class_name) {
            /* Find the class definition across the whole project */
            ClassNode *cn = find_class_in_project(proj, class_name);
            if (cn) {
                /* Emit public fields */
                for (int f = 0; f < cn->field_count && count < max_out; f++) {
                    FieldNode *fld = cn->fields[f];
                    if (!fld || !fld->is_public) continue;
                    char ft[64]; type_to_str(fld->field_type, ft, sizeof(ft));
                    char det[128];
                    snprintf(det, sizeof(det), "%s: %s", fld->name, ft);
                    out[count] = (CompletionItem){0};
                    snprintf(out[count].label,  sizeof(out[count].label),  "%s", fld->name);
                    snprintf(out[count].detail, sizeof(out[count].detail), "%s", det);
                    out[count].kind = COMPLETE_FIELD;
                    count++;
                }
                /* Emit methods */
                for (int m = 0; m < cn->method_count && count < max_out; m++) {
                    MethodNode *mn = cn->methods[m];
                    if (!mn) continue;
                    char ret[64]; type_to_str(mn->return_type, ret, sizeof(ret));
                    char sig[256];
                    build_sig(sig, sizeof(sig), ret, mn->name,
                              mn->params, mn->param_count);
                    out[count] = (CompletionItem){0};
                    snprintf(out[count].label,  sizeof(out[count].label),  "%s", mn->name);
                    snprintf(out[count].detail, sizeof(out[count].detail), "%s", sig);
                    out[count].kind = COMPLETE_METHOD;
                    count++;
                }
                if (count > 0) return count;
            }
        }
        /* Fall through to global if we couldn't resolve the type */
    }

    /* ── Global completions ── */

    /* Locals from the current file first */
    if (st->file)
        collect_locals(st->file->program, line, out, &count, max_out);

    /* Project-wide global symbols (keywords, builtins, all declared funcs/classes) */
    if (proj) {
        for (int i = 0; i < proj->global_completion_count && count < max_out; i++) {
            CompletionItem *src = &proj->global_completions[i];
            /* Deduplicate against what we already emitted as locals */
            int dup = 0;
            for (int j = 0; j < count; j++) {
                if (out[j].kind == src->kind &&
                    strcmp(out[j].label, src->label) == 0) { dup = 1; break; }
            }
            if (!dup)
                out[count++] = *src;
        }
    }

    return count;
}

/* ═══════════════════════════════════════════════════════════════════════════════
   Public: lsp_hover
   ═══════════════════════════════════════════════════════════════════════════════ */

HoverResult lsp_hover(LspState *st,
                       const char *source, int line, int col)
{
    HoverResult res = { 0, "" };
    if (!st) return res;

    char *word = word_at(source, line, col);
    if (!word) return res;

    LspProject *proj = st->project;

    /* ── Search order: current file, then all other project files ── */

    /* Build a search list: current file first */
    ProgramNode *search[MAX_PROJECT_FILES + 1];
    const char  *search_file[MAX_PROJECT_FILES + 1];
    int          search_count = 0;

    if (st->file && st->file->program) {
        search[search_count]      = st->file->program;
        search_file[search_count] = st->file->filepath;
        search_count++;
    }
    if (proj) {
        for (int f = 0; f < proj->file_count; f++) {
            if (st->file && &proj->files[f] == st->file) continue;
            if (!proj->files[f].program) continue;
            search[search_count]      = proj->files[f].program;
            search_file[search_count] = proj->files[f].filepath;
            search_count++;
        }
    }

    for (int si = 0; si < search_count; si++) {
        ProgramNode *prog     = search[si];
        const char  *src_file = search_file[si];

        /* Compute a short label for the source file */
        const char *src_label = src_file;
        if (proj) {
            int rlen = (int)strlen(proj->root_dir);
            if (strncmp(src_file, proj->root_dir, rlen) == 0 &&
                src_file[rlen] == '/')
                src_label = src_file + rlen + 1;
        }

        for (int i = 0; i < prog->decl_count; i++) {
            ASTNode *d = prog->declarations[i];
            if (!d) continue;

            /* ── Top-level function ── */
            if (d->type == NODE_FUNC) {
                FuncNode *fn = (FuncNode *)d;
                if (strcmp(fn->name, word) != 0) continue;

                char ret[64]; type_to_str(fn->return_type, ret, sizeof(ret));
                char sig[256]; build_sig(sig, sizeof(sig), ret, fn->name,
                                         fn->params, fn->param_count);
                snprintf(res.content, sizeof(res.content),
                         "```hylian\n%s\n```\n*from `%s`*", sig, src_label);
                res.found = 1;
                free(word);
                return res;
            }

            /* ── Class, method, or field ── */
            if (d->type == NODE_CLASS) {
                ClassNode *cn = (ClassNode *)d;

                if (strcmp(cn->name, word) == 0) {
                    snprintf(res.content, sizeof(res.content),
                             "```hylian\n%sclass %s\n```\n*from `%s`*",
                             cn->is_public ? "public " : "", cn->name, src_label);
                    res.found = 1;
                    free(word);
                    return res;
                }

                for (int m = 0; m < cn->method_count; m++) {
                    MethodNode *mn = cn->methods[m];
                    if (!mn || strcmp(mn->name, word) != 0) continue;

                    char ret[64]; type_to_str(mn->return_type, ret, sizeof(ret));
                    char sig[256]; build_sig(sig, sizeof(sig), ret, mn->name,
                                             mn->params, mn->param_count);
                    snprintf(res.content, sizeof(res.content),
                             "```hylian\n%s::%s\n```\n*method of `%s` from `%s`*",
                             cn->name, sig + strlen(ret) + 1,
                             cn->name, src_label);
                    res.found = 1;
                    free(word);
                    return res;
                }

                for (int f = 0; f < cn->field_count; f++) {
                    FieldNode *fld = cn->fields[f];
                    if (!fld || strcmp(fld->name, word) != 0) continue;

                    char ft[64]; type_to_str(fld->field_type, ft, sizeof(ft));
                    snprintf(res.content, sizeof(res.content),
                             "```hylian\n%s%s %s.%s\n```\n*field of `%s` from `%s`*",
                             fld->is_public ? "public " : "private ",
                             ft, cn->name, fld->name,
                             cn->name, src_label);
                    res.found = 1;
                    free(word);
                    return res;
                }
            }
        }
    }

    /* ── Built-ins ── */
    for (int i = 0; hylian_builtins[i].name; i++) {
        if (strcmp(hylian_builtins[i].name, word) == 0) {
            snprintf(res.content, sizeof(res.content),
                     "```hylian\n%s\n```\n*built-in function*",
                     hylian_builtins[i].detail);
            res.found = 1;
            free(word);
            return res;
        }
    }

    free(word);
    return res;
}