; Generated by Hylian compiler (asm backend)
; Source: /tmp/test_switch.hy
bits 64
default rel

; Target: linux
; Assemble: nasm -f elf64 <file>.asm -o <file>.o
; Link:     gcc <file>.o -o <program> -no-pie

extern malloc
extern strlen

section .data

section .text
    global main

main:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov rax, 1
    mov [rbp - 8], rax
    mov rax, [rbp - 8]
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    push rax
    mov rax, 0
    pop rcx
    cmp rcx, rax
    je .L2
    mov rax, [rbp - 16]
    push rax
    mov rax, 1
    pop rcx
    cmp rcx, rax
    je .L3
    jmp .L4
.L2:
    mov rax, 10
    mov [rbp - 8], rax
    jmp .L1
.L3:
    mov rax, 20
    mov [rbp - 8], rax
    jmp .L1
.L4:
    mov rax, 99
    mov [rbp - 8], rax
    jmp .L1
.L1:
    xor rax, rax
    mov rsp, rbp
    pop rbp
    ret

