#include "codegen.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "ast.h"

static const char *map_type(const char *t) {
    if (strcmp(t, "str") == 0)  return "std::string";
    if (strcmp(t, "bool") == 0) return "bool";
    if (strcmp(t, "auto") == 0) return "auto";
    return t;
}

/* Returns a heap-allocated C++ type string for a Type */
char *codegen_type(Type t) {
    if (t.kind == TYPE_SIMPLE) {
        const char *base = map_type(t.name);
        if (t.nullable) {
            /* pointer type: "T*" */
            size_t len = strlen(base) + 2;
            char *result = malloc(len);
            snprintf(result, len, "%s*", base);
            return result;
        } else {
            return strdup(base);
        }
    }

    if (t.kind == TYPE_ARRAY) {
        /* Get element type string */
        char *elem_str = codegen_type(t.elem_types[0]);
        char *result;
        if (t.fixed_size > 0) {
            /* std::array<T, N> */
            size_t len = strlen("std::array<") + strlen(elem_str) + 32;
            result = malloc(len);
            snprintf(result, len, "std::array<%s, %d>", elem_str, t.fixed_size);
        } else {
            /* std::vector<T> */
            size_t len = strlen("std::vector<") + strlen(elem_str) + 2;
            result = malloc(len);
            snprintf(result, len, "std::vector<%s>", elem_str);
        }
        free(elem_str);
        return result;
    }

    if (t.kind == TYPE_MULTI) {
        char *inner;
        if (t.is_any) {
            inner = strdup("std::any");
        } else {
            /* Build std::variant<A, B, ...> */
            /* First compute total length */
            char **elem_strs = malloc(t.elem_type_count * sizeof(char *));
            size_t total = strlen("std::variant<") + 1;
            for (int i = 0; i < t.elem_type_count; i++) {
                elem_strs[i] = codegen_type(t.elem_types[i]);
                total += strlen(elem_strs[i]) + 2; /* ", " */
            }
            inner = malloc(total);
            strcpy(inner, "std::variant<");
            for (int i = 0; i < t.elem_type_count; i++) {
                strcat(inner, elem_strs[i]);
                if (i < t.elem_type_count - 1) strcat(inner, ", ");
                free(elem_strs[i]);
            }
            strcat(inner, ">");
            free(elem_strs);
        }

        char *result;
        if (t.fixed_size > 0) {
            size_t len = strlen("std::array<") + strlen(inner) + 32;
            result = malloc(len);
            snprintf(result, len, "std::array<%s, %d>", inner, t.fixed_size);
        } else {
            size_t len = strlen("std::vector<") + strlen(inner) + 2;
            result = malloc(len);
            snprintf(result, len, "std::vector<%s>", inner);
        }
        free(inner);
        return result;
    }

    return strdup("/* unknown type */");
}

static void indent(int depth, FILE *out) {
    for (int i = 0; i < depth; i++) fprintf(out, "    ");
}

void codegen_args(ASTNode **args, int count, FILE *out) {
    for (int i = 0; i < count; i++) {
        codegen_expr(args[i], out);
        if (i < count - 1) fprintf(out, ", ");
    }
}

static void emit_params(ASTNode **params, int count, FILE *out) {
    for (int i = 0; i < count; i++) {
        VarDeclNode *p = (VarDeclNode *)params[i];
        char *type_str = codegen_type(p->var_type);
        fprintf(out, "%s %s", type_str, p->var_name);
        free(type_str);
        if (i < count - 1) fprintf(out, ", ");
    }
}

static void emit_body(ASTNode **body, int count, FILE *out, int depth) {
    for (int i = 0; i < count; i++) {
        indent(depth, out);
        codegen_stmt(body[i], out, depth);
    }
}

void codegen(ProgramNode *root, FILE *out) {
    fprintf(out, "// Generated by Hylian compiler\n");
    fprintf(out, "#include <string>\n");
    fprintf(out, "#include <sstream>\n");
    fprintf(out, "#include <memory>\n");
    fprintf(out, "#include <optional>\n");
    fprintf(out, "#include <functional>\n");
    fprintf(out, "#include <vector>\n");
    fprintf(out, "#include <array>\n");
    fprintf(out, "#include <variant>\n");
    fprintf(out, "#include <any>\n");
    fprintf(out, "\n");

    fprintf(out, "struct Error {\n");
    fprintf(out, "    std::string message;\n");
    fprintf(out, "    Error(const std::string& msg) : message(msg) {}\n");
    fprintf(out, "};\n\n");

    /* Forward declare classes */
    for (int i = 0; i < root->decl_count; i++) {
        if (root->declarations[i]->type == NODE_CLASS)
            fprintf(out, "class %s;\n", ((ClassNode *)root->declarations[i])->name);
    }
    fprintf(out, "\n");

    for (int i = 0; i < root->decl_count; i++) {
        ASTNode *d = root->declarations[i];
        if (d->type == NODE_CLASS) codegen_class((ClassNode *)d, out);
    }
    for (int i = 0; i < root->decl_count; i++) {
        ASTNode *d = root->declarations[i];
        if (d->type == NODE_FUNC) codegen_func((FuncNode *)d, out);
    }
}

void codegen_class(ClassNode *cls, FILE *out) {
    fprintf(out, "class %s {\n", cls->name);

    /* Private fields */
    int has_private = 0;
    for (int i = 0; i < cls->field_count; i++)
        if (!cls->fields[i]->is_public) { has_private = 1; break; }

    if (has_private) {
        fprintf(out, "private:\n");
        for (int i = 0; i < cls->field_count; i++)
            if (!cls->fields[i]->is_public) {
                fprintf(out, "    ");
                codegen_field(cls->fields[i], out);
            }
    }

    fprintf(out, "public:\n");

    /* Public fields */
    for (int i = 0; i < cls->field_count; i++)
        if (cls->fields[i]->is_public) {
            fprintf(out, "    ");
            codegen_field(cls->fields[i], out);
        }

    /* Constructor */
    if (cls->has_ctor) {
        fprintf(out, "    %s(", cls->name);
        emit_params(cls->ctor_params, cls->ctor_param_count, out);
        fprintf(out, ") {\n");
        emit_body(cls->ctor_body, cls->ctor_body_count, out, 2);
        fprintf(out, "    }\n");
    }

    /* Methods */
    for (int i = 0; i < cls->method_count; i++) {
        fprintf(out, "    ");
        codegen_method(cls->methods[i], out);
    }

    fprintf(out, "};\n\n");
}

void codegen_field(FieldNode *field, FILE *out) {
    char *type_str = codegen_type(field->field_type);
    fprintf(out, "%s %s;\n", type_str, field->name);
    free(type_str);
}

void codegen_method(MethodNode *method, FILE *out) {
    char *ret = codegen_type(method->return_type);
    if (method->return_type.nullable)
        fprintf(out, "%s* %s(", ret, method->name);
    else
        fprintf(out, "%s %s(", ret, method->name);
    free(ret);
    emit_params(method->params, method->param_count, out);
    fprintf(out, ") {\n");
    emit_body(method->body, method->body_count, out, 2);
    fprintf(out, "    }\n");
}

static int is_main_func(FuncNode *func) {
    return strcmp(func->name, "main") == 0;
}

static void emit_body_main(ASTNode **body, int count, FILE *out, int depth) {
    for (int i = 0; i < count; i++) {
        /* Convert "return nil/nullptr" to "return 0" inside main */
        if (body[i]->type == NODE_RETURN) {
            ReturnNode *r = (ReturnNode *)body[i];
            if (!r->value ||
                (r->value->type == NODE_LITERAL &&
                 ((LiteralNode *)r->value)->lit_type == LIT_NIL)) {
                indent(depth, out);
                fprintf(out, "return 0;\n");
                continue;
            }
        }
        indent(depth, out);
        codegen_stmt(body[i], out, depth);
    }
}

void codegen_func(FuncNode *func, FILE *out) {
    /* Special-case: void main() or Error? main() -> int main() */
    if (is_main_func(func)) {
        fprintf(out, "int main(");
        emit_params(func->params, func->param_count, out);
        fprintf(out, ") {\n");
        emit_body_main(func->body, func->body_count, out, 1);
        fprintf(out, "}\n\n");
        return;
    }
    char *ret = codegen_type(func->return_type);
    if (func->return_type.nullable)
        fprintf(out, "%s* %s(", ret, func->name);
    else
        fprintf(out, "%s %s(", ret, func->name);
    free(ret);
    emit_params(func->params, func->param_count, out);
    fprintf(out, ") {\n");
    emit_body(func->body, func->body_count, out, 1);
    fprintf(out, "}\n\n");
}

void codegen_stmt(ASTNode *stmt, FILE *out, int depth) {
    switch (stmt->type) {
    case NODE_RETURN: {
        ReturnNode *r = (ReturnNode *)stmt;
        fprintf(out, "return");
        if (r->value) { fprintf(out, " "); codegen_expr(r->value, out); }
        fprintf(out, ";\n");
        break;
    }
    case NODE_VAR_DECL: {
        VarDeclNode *v = (VarDeclNode *)stmt;
        char *type_str = codegen_type(v->var_type);
        fprintf(out, "%s %s", type_str, v->var_name);
        free(type_str);
        if (v->initializer) {
            /* For array literals, use brace-init directly */
            if (v->initializer->type == NODE_ARRAY_LITERAL) {
                fprintf(out, " = {");
                ArrayLiteralNode *al = (ArrayLiteralNode *)v->initializer;
                for (int i = 0; i < al->elem_count; i++) {
                    codegen_expr(al->elements[i], out);
                    if (i < al->elem_count - 1) fprintf(out, ", ");
                }
                fprintf(out, "}");
            } else {
                fprintf(out, " = ");
                codegen_expr(v->initializer, out);
            }
        }
        fprintf(out, ";\n");
        break;
    }
    case NODE_ASSIGN: {
        AssignNode *a = (AssignNode *)stmt;
        fprintf(out, "%s = ", a->var_name);
        codegen_expr(a->value, out);
        fprintf(out, ";\n");
        break;
    }
    case NODE_COMPOUND_ASSIGN: {
        CompoundAssignNode *ca = (CompoundAssignNode *)stmt;
        fprintf(out, "%s %s ", ca->var_name, ca->op);
        codegen_expr(ca->value, out);
        fprintf(out, ";\n");
        break;
    }
    case NODE_MEMBER_ASSIGN: {
        MemberAssignNode *ma = (MemberAssignNode *)stmt;
        if (ma->object) { codegen_expr(ma->object, out); fprintf(out, "."); }
        fprintf(out, "%s = ", ma->member);
        codegen_expr(ma->value, out);
        fprintf(out, ";\n");
        break;
    }
    case NODE_INDEX_ASSIGN: {
        IndexAssignNode *ia = (IndexAssignNode *)stmt;
        codegen_expr(ia->object, out);
        fprintf(out, "[");
        codegen_expr(ia->index, out);
        fprintf(out, "] = ");
        codegen_expr(ia->value, out);
        fprintf(out, ";\n");
        break;
    }
    case NODE_IF: {
        IfNode *ifn = (IfNode *)stmt;
        fprintf(out, "if (");
        codegen_expr(ifn->condition, out);
        fprintf(out, ") {\n");
        emit_body(ifn->then_body, ifn->then_count, out, depth + 1);
        indent(depth, out);
        fprintf(out, "}");
        if (ifn->else_count > 0) {
            fprintf(out, " else {\n");
            emit_body(ifn->else_body, ifn->else_count, out, depth + 1);
            indent(depth, out);
            fprintf(out, "}");
        }
        fprintf(out, "\n");
        break;
    }
    case NODE_WHILE: {
        WhileNode *wn = (WhileNode *)stmt;
        fprintf(out, "while (");
        codegen_expr(wn->condition, out);
        fprintf(out, ") {\n");
        emit_body(wn->body, wn->body_count, out, depth + 1);
        indent(depth, out);
        fprintf(out, "}\n");
        break;
    }
    case NODE_FOR: {
        ForNode *fn = (ForNode *)stmt;
        fprintf(out, "for (");
        if (fn->init) {
            if (fn->init->type == NODE_VAR_DECL) {
                VarDeclNode *v = (VarDeclNode *)fn->init;
                char *type_str = codegen_type(v->var_type);
                fprintf(out, "%s %s", type_str, v->var_name);
                free(type_str);
                if (v->initializer) { fprintf(out, " = "); codegen_expr(v->initializer, out); }
            } else if (fn->init->type == NODE_ASSIGN) {
                AssignNode *a = (AssignNode *)fn->init;
                fprintf(out, "%s = ", a->var_name);
                codegen_expr(a->value, out);
            } else {
                codegen_expr(fn->init, out);
            }
        }
        fprintf(out, "; ");
        if (fn->condition) codegen_expr(fn->condition, out);
        fprintf(out, "; ");
        if (fn->post) codegen_expr(fn->post, out);
        fprintf(out, ") {\n");
        emit_body(fn->body, fn->body_count, out, depth + 1);
        indent(depth, out);
        fprintf(out, "}\n");
        break;
    }
    case NODE_BREAK:
        fprintf(out, "break;\n");
        break;
    case NODE_CONTINUE:
        fprintf(out, "continue;\n");
        break;
    case NODE_DEFER: {
        DeferNode *dn = (DeferNode *)stmt;
        fprintf(out, "struct _D%p{std::function<void()>f;~_D%p(){f();}}_d%p{[&](){",
                (void*)stmt,(void*)stmt,(void*)stmt);
        codegen_expr(dn->expr, out);
        fprintf(out, ";}}; \n");
        break;
    }
    default:
        codegen_expr(stmt, out);
        fprintf(out, ";\n");
        break;
    }
}

void codegen_expr(ASTNode *expr, FILE *out) {
    switch (expr->type) {
    case NODE_LITERAL: {
        LiteralNode *lit = (LiteralNode *)expr;
        if (lit->lit_type == LIT_NIL)  fprintf(out, "nullptr");
        else                            fprintf(out, "%s", lit->value);
        break;
    }
    case NODE_IDENTIFIER:
        fprintf(out, "%s", ((IdentifierNode *)expr)->name);
        break;
    case NODE_BINARY_OP: {
        BinaryOpNode *b = (BinaryOpNode *)expr;
        fprintf(out, "(");
        codegen_expr(b->left, out);
        fprintf(out, " %s ", b->op);
        codegen_expr(b->right, out);
        fprintf(out, ")");
        break;
    }
    case NODE_UNARY_OP: {
        UnaryOpNode *u = (UnaryOpNode *)expr;
        if (u->postfix) {
            codegen_expr(u->operand, out);
            fprintf(out, "%s", u->op);
        } else {
            fprintf(out, "%s", u->op);
            codegen_expr(u->operand, out);
        }
        break;
    }
    case NODE_MEMBER_ACCESS: {
        MemberAccessNode *m = (MemberAccessNode *)expr;
        codegen_expr(m->object, out);
        fprintf(out, ".%s", m->member);
        break;
    }
    case NODE_METHOD_CALL: {
        MethodCallNode *c = (MethodCallNode *)expr;
        codegen_expr(c->object, out);
        fprintf(out, ".%s(", c->method);
        codegen_args(c->args, c->arg_count, out);
        fprintf(out, ")");
        break;
    }
    case NODE_FUNC_CALL: {
        FuncCallNode *c = (FuncCallNode *)expr;
        fprintf(out, "%s(", c->name);
        codegen_args(c->args, c->arg_count, out);
        fprintf(out, ")");
        break;
    }
    case NODE_NEW: {
        NewNode *n = (NewNode *)expr;
        fprintf(out, "%s(", n->class_name);
        codegen_args(n->args, n->arg_count, out);
        fprintf(out, ")");
        break;
    }
    case NODE_MEMBER_ASSIGN: {
        MemberAssignNode *ma = (MemberAssignNode *)expr;
        if (ma->object) { codegen_expr(ma->object, out); fprintf(out, "."); }
        fprintf(out, "%s = ", ma->member);
        codegen_expr(ma->value, out);
        break;
    }
    case NODE_ARRAY_LITERAL: {
        ArrayLiteralNode *al = (ArrayLiteralNode *)expr;
        fprintf(out, "{");
        for (int i = 0; i < al->elem_count; i++) {
            codegen_expr(al->elements[i], out);
            if (i < al->elem_count - 1) fprintf(out, ", ");
        }
        fprintf(out, "}");
        break;
    }
    case NODE_INDEX: {
        IndexNode *idx = (IndexNode *)expr;
        codegen_expr(idx->object, out);
        fprintf(out, "[");
        codegen_expr(idx->index, out);
        fprintf(out, "]");
        break;
    }
    case NODE_INTERP_STRING: {
        InterpStringNode *is = (InterpStringNode *)expr;
        /* Use ostringstream so any streamable type works (int, str, float, etc.) */
        fprintf(out, "([&]() -> std::string { std::ostringstream _oss; ");
        for (int i = 0; i < is->seg_count; i++) {
            InterpSegment *seg = &is->segments[i];
            if (seg->is_expr) {
                fprintf(out, "_oss << (%s); ", seg->text);
            } else {
                fprintf(out, "_oss << \"");
                for (char *c = seg->text; *c; c++) {
                    if (*c == '"')       fprintf(out, "\\\"");
                    else if (*c == '\\') fprintf(out, "\\\\");
                    else if (*c == '\n') fprintf(out, "\\n");
                    else if (*c == '\t') fprintf(out, "\\t");
                    else                 fputc(*c, out);
                }
                fprintf(out, "\"; ");
            }
        }
        fprintf(out, "return _oss.str(); }())");
        break;
    }
    default:
        fprintf(out, "/* unknown expr */");
        break;
    }
}
