#include "codegen.h"
#include <string.h>

void codegen(ProgramNode* root, FILE* out) {
    // Generated header
    fprintf(out, "// Generated by Hylian compiler\n");
    fprintf(out, "#include <string>\n");
    fprintf(out, "#include <memory>\n\n");
    
    // Generate all classes
    for (int i = 0; i < root->decl_count; i++) {
        ASTNode* decl = root->declarations[i];
        if (decl->type == NODE_CLASS) {
            codegen_class((ClassNode*)decl, out);
        }
    }
}

void codegen_class(ClassNode* cls, FILE* out) {
    fprintf(out, "class %s {\n", cls->name);
    
    // Private fields
    if (cls->field_count > 0) {
        fprintf(out, "private:\n");
        for (int i = 0; i < cls->field_count; i++) {
            if (!cls->fields[i]->is_public) {
                fprintf(out, "    ");
                codegen_field(cls->fields[i], out);
            }
        }
    }
    
    // Public section
    fprintf(out, "public:\n");
    
    // Public fields
    for (int i = 0; i < cls->field_count; i++) {
        if (cls->fields[i]->is_public) {
            fprintf(out, "    ");
            codegen_field(cls->fields[i], out);
        }
    }
    
    // Methods
    for (int i = 0; i < cls->method_count; i++) {
        fprintf(out, "    ");
        codegen_method(cls->methods[i], cls->name, out);
    }
    
    fprintf(out, "};\n\n");
}

void codegen_field(FieldNode* field, FILE* out) {
    // Map Hylian types to C++
    const char* cpp_type = field->field_type.name;
    if (strcmp(cpp_type, "str") == 0) {
        cpp_type = "std::string";
    }
    
    fprintf(out, "%s %s;\n", cpp_type, field->name);
}

void codegen_method(MethodNode* method, const char* class_name, FILE* out) {
    // Return type
    const char* ret_type = method->return_type.name;
    if (strcmp(ret_type, "str") == 0) {
        ret_type = "std::string";
    }
    
    // Handle Error? -> use std::optional or just Error* for now
    if (method->return_type.nullable) {
        fprintf(out, "%s* %s(", ret_type, method->name);
    } else {
        fprintf(out, "%s %s(", ret_type, method->name);
    }
    
    // Parameters (TODO)
    fprintf(out, ") {\n");
    
    // Body
    for (int i = 0; i < method->body_count; i++) {
        fprintf(out, "        ");
        codegen_stmt(method->body[i], out);
    }
    
    fprintf(out, "    }\n");
}

void codegen_stmt(ASTNode* stmt, FILE* out) {
    switch (stmt->type) {
        case NODE_RETURN: {
            ReturnNode* ret = (ReturnNode*)stmt;
            fprintf(out, "return");
            if (ret->value) {
                fprintf(out, " ");
                codegen_expr(ret->value, out);
            }
            fprintf(out, ";\n");
            break;
        }
        
        case NODE_VAR_DECL: {
            VarDeclNode* var = (VarDeclNode*)stmt;
            const char* type = var->var_type.name;
            if (strcmp(type, "str") == 0) type = "std::string";
            
            fprintf(out, "%s %s", type, var->var_name);
            if (var->initializer) {
                fprintf(out, " = ");
                codegen_expr(var->initializer, out);
            }
            fprintf(out, ";\n");
            break;
        }
        
        case NODE_ASSIGN: {
            AssignNode* assign = (AssignNode*)stmt;
            fprintf(out, "%s = ", assign->var_name);
            codegen_expr(assign->value, out);
            fprintf(out, ";\n");
            break;
        }
        
        case NODE_IF: {
            IfNode* ifn = (IfNode*)stmt;
            fprintf(out, "if (");
            codegen_expr(ifn->condition, out);
            fprintf(out, ") {\n");
            for (int i = 0; i < ifn->then_count; i++) {
                fprintf(out, "            ");
                codegen_stmt(ifn->then_body[i], out);
            }
            fprintf(out, "        }");
            if (ifn->else_count > 0) {
                fprintf(out, " else {\n");
                for (int i = 0; i < ifn->else_count; i++) {
                    fprintf(out, "            ");
                    codegen_stmt(ifn->else_body[i], out);
                }
                fprintf(out, "        }");
            }
            fprintf(out, "\n");
            break;
        }
        
        case NODE_WHILE: {
            WhileNode* wn = (WhileNode*)stmt;
            fprintf(out, "while (");
            codegen_expr(wn->condition, out);
            fprintf(out, ") {\n");
            for (int i = 0; i < wn->body_count; i++) {
                fprintf(out, "            ");
                codegen_stmt(wn->body[i], out);
            }
            fprintf(out, "        }\n");
            break;
        }
        
        default:
            // Expression statement
            codegen_expr(stmt, out);
            fprintf(out, ";\n");
            break;
    }
}

void codegen_expr(ASTNode* expr, FILE* out) {
    switch (expr->type) {
        case NODE_LITERAL: {
            LiteralNode* lit = (LiteralNode*)expr;
            if (lit->lit_type == LIT_STRING) {
                fprintf(out, "%s", lit->value);
            } else if (lit->lit_type == LIT_NIL) {
                fprintf(out, "nullptr");
            } else {
                fprintf(out, "%s", lit->value);
            }
            break;
        }
        
        case NODE_IDENTIFIER: {
            IdentifierNode* id = (IdentifierNode*)expr;
            fprintf(out, "%s", id->name);
            break;
        }
        
        case NODE_BINARY_OP: {
            BinaryOpNode* bin = (BinaryOpNode*)expr;
            codegen_expr(bin->left, out);
            fprintf(out, " %s ", bin->op);
            codegen_expr(bin->right, out);
            break;
        }
        
        case NODE_MEMBER_ACCESS: {
            MemberAccessNode* mem = (MemberAccessNode*)expr;
            codegen_expr(mem->object, out);
            fprintf(out, ".%s", mem->member);
            break;
        }
        
        case NODE_METHOD_CALL: {
            MethodCallNode* call = (MethodCallNode*)expr;
            codegen_expr(call->object, out);
            fprintf(out, ".%s(", call->method);
            // TODO: args
            fprintf(out, ")");
            break;
        }
        
        default:
            fprintf(out, "/* unknown expr */");
            break;
    }
}
